/** Shared row order for planets + angles + minor bodies on chart tables and wheel. */
export const CHART_POINT_ORDER: string[] = [
  "sun",
  "moon",
  "ascendant",
  "mercury",
  "venus",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
  "pluto",
  "chiron",
  "midheaven",
  "ceres",
  "pallas",
  "juno",
  "vesta",
  "north_node",
  "south_node",
  "lilith",
  "part_of_fortune",
];
