from django.urls import include, path

urlpatterns = [
    path("slack/", include("slack_integration.urls")),
    path("contact/", include("contact.urls")),
    path("meal/", include("meal.urls")),
    path("users/", include("users.urls")),
    path("quotes/", include("quotes.urls")),
    path("friends/", include("friends.urls")),
    path("whatif/", include("whatif.urls")),
    path("clicker/", include("clicker.urls")),
    path("clicker2/", include("clicker.clicker2_urls")),
    path("achievements/", include("achievements.urls")),
    path("qff/", include("qff.urls")),
    path("closet/", include("closet.urls")),
    path("songaday/", include("songaday.urls")),
    path("friend-comments/", include("friend_comments.urls")),
    path("calendars/", include("calendars.urls")),
    path("harbor/", include("harbor.urls")),
    path("pondstead/", include("pondstead.urls")),
    path("zodiac/", include("zodiac.urls")),
    path("people/", include("people.urls")),
    path("estates/", include("estates.urls")),
    path("goals/", include("goals.urls")),
    path("scorenado/", include("scorenado.urls")),
    path("recommendations/", include("recommendations.urls")),
]
