from django.urls import path

from meal import views, views_partner

urlpatterns = [
    path("bootstrap/", views.meal_bootstrap),
    path("meals/", views.meal_list_create),
    path("meals/shared/", views.meal_shared_list),
    path("meals/import/", views.meal_import_from_url),
    path("paprika/import/", views.meal_import_paprika),
    path("uploads/presign/", views.meal_uploads_presign),
    path("meals/tags/", views.meal_tag_vocab),
    path("meals/tags/seed/", views.meal_tag_seed),
    path("meals/category-options/", views.meal_category_options_list),
    path("meals/<int:pk>/", views.meal_detail),
    path("meals/<int:pk>/copy/", views.meal_copy_from_friend),
    path("instances/", views.instance_list_create),
    path("instances/<int:pk>/", views.instance_detail),
    path("instances/<int:pk>/grid/", views.instance_grid),
    path("instances/<int:pk>/grocery/generate/", views.grocery_generate),
    path("instances/<int:pk>/grocery/", views.instance_grocery_retrieve),
    path("grocery/<int:pk>/", views.grocery_detail),
    path("grocery/<int:pk>/items/", views.grocery_list_add_item),
    path("grocery/items/<int:item_id>/", views.grocery_list_item_patch),
    path("grocery/saved/", views.saved_grocery_list),
    path("grocery/saved/<int:pk>/", views.saved_grocery_detail),
    path("ingredients/", views.ingredient_vocab),
    path("ingredients/<int:pk>/", views.ingredient_detail),
    path("pantry/inventory/", views.pantry_inventory_list),
    path("pantry/inventory/upsert/", views.pantry_inventory_put),
    path("pantry/inventory/parse/", views.pantry_inventory_parse),
    path("pantry/inventory/import/", views.pantry_inventory_import),
    path("partner/disconnect/request/", views_partner.disconnect_request),
    path("partner/disconnect/cancel/", views_partner.disconnect_cancel),
    path("partner/disconnect/confirm/", views_partner.disconnect_confirm),
    path("partner/disconnect/pending/", views_partner.disconnect_pending),
    path("partner/request/decline/", views_partner.decline_incoming_partner_request),
]
