import { denizenDoubleEfficiencyEffectText, getDenizenDef } from "./denizens";
import { DENIZEN_EVOLUTION_TIER_MULT } from "./evolutionTierMults";
import { specialtyCatalogPrice } from "./evolutionPrices.generated";

export type SpecialtyEffect =
  | { type: "double_click_and_denizen"; denizenId: string }
  | { type: "double_denizen"; denizenId: string }
  | { type: "concentric_rings" }
  | { type: "concentric_rings_mult"; factor: number }
  | { type: "production_percent"; percent: number };

export type SpecialtyDef = {
  id: number;
  name: string;
  denizenId: string;
  /** Owned count of `denizenId` required when `unlockAllTimeEnergy` is unset. */
  unlockOwned: number;
  /** Pond production tiers: unlock when all-time energy earned reaches this value. */
  unlockAllTimeEnergy?: number;
  price: number;
  effect: SpecialtyEffect;
  effectText: string;
  ecologyNote: string;
};

function rippleClick(
  id: number,
  name: string,
  unlock: number,
  ecologyNote: string,
): SpecialtyDef {
  return {
    id,
    name,
    denizenId: "ripples",
    unlockOwned: unlock,
    price: specialtyCatalogPrice(id),
    effect: { type: "double_click_and_denizen", denizenId: "ripples" },
    effectText: "Mouse click and Ripples are twice as efficient",
    ecologyNote,
  };
}

function doubleDenizen(
  id: number,
  name: string,
  denizenId: string,
  unlock: number,
  price: number,
  ecologyNote: string,
): SpecialtyDef {
  const def = getDenizenDef(denizenId);
  const effectText = def
    ? denizenDoubleEfficiencyEffectText(def)
    : "Denizens are twice as efficient";
  return {
    id,
    name,
    denizenId,
    unlockOwned: unlock,
    price,
    effect: { type: "double_denizen", denizenId },
    effectText,
    ecologyNote,
  };
}

/** Owned denizen count required per specialty tier index (0–14) within a denizen chain. */
export const DENIZEN_SPECIALTY_UNLOCK_TIER = [
  1, 5, 25, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600,
] as const;

const UNLOCK_TIER = DENIZEN_SPECIALTY_UNLOCK_TIER;

/** Pond-wide production specialties (not tied to a denizen owned count). */
export const POND_SPECIALTY_DENIZEN_ID = "pond" as const;

/** Canonical evolution tier multipliers (price = round(baseCost × mult)). */
export const DENIZEN_SPECIALTY_COST_MULT = DENIZEN_EVOLUTION_TIER_MULT;

export function specialtyPriceForDenizenTier(
  baseCost: number,
  tierIndex: number,
): number {
  const mult =
    DENIZEN_EVOLUTION_TIER_MULT[tierIndex] ??
    DENIZEN_EVOLUTION_TIER_MULT[DENIZEN_EVOLUTION_TIER_MULT.length - 1]!;
  return Math.round(baseCost * mult);
}

/** All-time energy earned to unlock each pond production tier (18 tiers). */
export const POND_UNLOCK_ENERGY = [
  50_000,
  250_000,
  500_000,
  2_500_000,
  12_500_000,
  25_000_000,
  125_000_000,
  625_000_000,
  1_250_000_000,
  6_250_000_000,
  31_250_000_000,
  62_500_000_000,
  312_500_000_000,
  1_562_500_000_000,
  3_125_000_000_000,
  15_625_000_000_000,
  31_250_000_000_000,
  156_250_000_000_000,
] as const;

/** New ids 166–168 preserve existing saves on legacy pond tiers 121–135. */
const POND_PRODUCTION_IDS = [
  166, 167, 168, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
  133, 134, 135,
] as const;

/** Tiers 0–2: +1%; tiers 3–17: +2% each. */
function pondProductionPercentForTierIndex(tierIndex: number): number {
  return tierIndex < 3 ? 1 : 2;
}

function productionPercentSpecialty(
  id: number,
  name: string,
  denizenId: string,
  tierIndex: number,
  price: number,
  ecologyNote: string,
  unlock: { unlockOwned: number } | { unlockAllTimeEnergy: number },
): SpecialtyDef {
  const percent = pondProductionPercentForTierIndex(tierIndex);
  return {
    id,
    name,
    denizenId,
    unlockOwned: "unlockOwned" in unlock ? unlock.unlockOwned : 0,
    unlockAllTimeEnergy:
      "unlockAllTimeEnergy" in unlock ? unlock.unlockAllTimeEnergy : undefined,
    price,
    effect: { type: "production_percent", percent },
    effectText: `+${percent}% energy production multiplier`,
    ecologyNote,
  };
}

function buildPondProductionChain(
  ecologyNotes: readonly string[],
  names: readonly string[],
): SpecialtyDef[] {
  return POND_UNLOCK_ENERGY.map((unlockAllTimeEnergy, i) =>
    productionPercentSpecialty(
      POND_PRODUCTION_IDS[i]!,
      names[i] ?? `Production ${i + 1}`,
      POND_SPECIALTY_DENIZEN_ID,
      i,
      specialtyCatalogPrice(POND_PRODUCTION_IDS[i]!),
      ecologyNotes[i] ?? "",
      { unlockAllTimeEnergy },
    ),
  );
}

export const SPECIALTIES: readonly SpecialtyDef[] = [
  rippleClick(
    1,
    "Surface Tension",
    UNLOCK_TIER[0],
    "Water striders and whirligig beetles skate the film as if the pond were glass. Molecules at the air–water interface cling together, holding droplets and meniscus life in place.",
  ),
  rippleClick(
    2,
    "Capillary Action",
    UNLOCK_TIER[1],
    "You can watch moisture creep up stems and along litter at the shore. Fine pores pull water against gravity, wicking nutrients where roots and microbes can reach them.",
  ),
  rippleClick(
    3,
    "Wind Ruffles",
    UNLOCK_TIER[2],
    "A breeze roughens the still surface and sends rings chasing each other across the pond. The film mixes oxygen into the top millimeters while pollen and dust ride the waves.",
  ),
  {
    id: 4,
    name: "Concentric Rings",
    denizenId: "ripples",
    unlockOwned: UNLOCK_TIER[3],
    price: specialtyCatalogPrice(4),
    effect: { type: "concentric_rings" },
    effectText:
      "Clicks and Ripples gain +0.1 energy for each non-Ripple object owned",
    ecologyNote:
      "Every click sends rings outward—and each new neighbor in the pond adds another edge for exchange. Disturbances stack as the basin fills with life.",
  },
  {
    id: 5,
    name: "Bottom Seep",
    denizenId: "ripples",
    unlockOwned: 50,
    price: specialtyCatalogPrice(5),
    effect: { type: "concentric_rings_mult", factor: 5 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 5",
    ecologyNote:
      "Cold water oozes up through gravel and clay, nudging the surface from below in slow pulses. Groundwater seeps feed the basin and spread subtle rings across the bottom.",
  },
  {
    id: 6,
    name: "Clear Inlet",
    denizenId: "ripples",
    unlockOwned: 100,
    price: specialtyCatalogPrice(6),
    effect: { type: "concentric_rings_mult", factor: 10 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 10",
    ecologyNote:
      "A clean channel from the watershed pours steady inflow that fans into overlapping wave fronts. Each new liter arriving sends ripples crossing the open water.",
  },
  {
    id: 7,
    name: "Spring Bulge",
    denizenId: "ripples",
    unlockOwned: 150,
    price: specialtyCatalogPrice(7),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Mineral-rich spring water swells the surface into a dome before long-lived rings radiate outward. Upwelling plumes bulge the film and push pulses across the pond.",
  },
  {
    id: 8,
    name: "Smooth Current",
    denizenId: "ripples",
    unlockOwned: 200,
    price: specialtyCatalogPrice(8),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Glassy parallel currents slide past snags and stems, shedding orderly waves that travel far. Even tiny obstacles in laminar flow send rings to the margin before they fade.",
  },
  {
    id: 9,
    name: "Gravel Riffle",
    denizenId: "ripples",
    unlockOwned: 250,
    price: specialtyCatalogPrice(9),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Shallow bars sparkle as water tumbles over gravel, throwing trains of small waves shoreward. Each riffle crest stitches the littoral to the open pond with fresh rings.",
  },
  {
    id: 10,
    name: "Spillway Drum",
    denizenId: "ripples",
    unlockOwned: 300,
    price: specialtyCatalogPrice(10),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Excess flow slips over a low dam and hammers a standing wave that drums through the whole basin. The overfall sends rhythmic pulses and concentric rings across the surface.",
  },
  {
    id: 11,
    name: "Deep Press",
    denizenId: "ripples",
    unlockOwned: 350,
    price: specialtyCatalogPrice(11),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "The weight of the water column presses on mud and roots, nudging the surface when depth shifts. Hydrostatic pressure and seasonal storage make the pond breathe in slow rings.",
  },
  {
    id: 12,
    name: "Layered Pond",
    denizenId: "ripples",
    unlockOwned: 400,
    price: specialtyCatalogPrice(12),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "A warm cap rides over cold deep water until wind or cooling breaks the stack. Thermal overturn sends one heavy surge—and a single set of rings—across the whole pond.",
  },
  {
    id: 13,
    name: "Sloshing Shore",
    denizenId: "ripples",
    unlockOwned: 450,
    price: specialtyCatalogPrice(13),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Wind piles water against one bank until gravity slings it back, rocking the basin for hours. A seiche sets up overlapping rings that cross and recross the surface.",
  },
  {
    id: 14,
    name: "Two Streams Meet",
    denizenId: "ripples",
    unlockOwned: 500,
    price: specialtyCatalogPrice(14),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Two drainages mingle at the lip, colliding currents that fan out in multiplied wave patterns. Confluence sends fresh rings racing across the open pond.",
  },
  {
    id: 15,
    name: "Step Pools",
    denizenId: "ripples",
    unlockOwned: 550,
    price: specialtyCatalogPrice(15),
    effect: { type: "concentric_rings_mult", factor: 20 },
    effectText: "Multiplies Concentric Rings click and Ripple gains by 20",
    ecologyNote:
      "Terraced pools overflow one into the next, each step tossing a new burst of rings. Cascades below the main basin echo pulses back into the parent pond.",
  },

  ...buildPondProductionChain(
    [
      "A shallow gleam appears where seeps meet—barely a pond yet, but enough water for life to notice. Those first pools concentrate runoff and begin storing energy along the basin floor.",
      "Trickles widen the wet spot until the hollow holds a steady shine after rain uphill. Watershed seepage links the surrounding land to this lowest gathering place.",
      "Water rises quietly from below, holding the surface up through dry weeks. A groundwater lens swells beneath the basin and steadies the bowl you are building.",
      "A sunlit shelf forms as silt settles in a scooped basin left by ice or old flow. Still water defines a shallow margin where plants and animals will soon crowd the edge.",
      "Each storm sends a pulse of rain across the surface, stirring pollen, dust, and fresh nutrients. Catchment runoff delivers sediment and dissolved organic matter with every shower.",
      "Green film and tiny plants begin to grow from the pond itself, not just from streams in. Algae and rooted producers fix carbon inside the basin and feed the local food web.",
      "You can read fertility in the water—gin-clear one season, pea-green the next. Chlorophyll, clarity, and nutrient balance sketch the pond's trophic state.",
      "Bubbles of oxygen build under sunny afternoons and fade in the deep at night. That daily rhythm decides where fish, insects, and microbes can breathe and feed.",
      "Soft bottom muck stores carbon while slowly releasing gases through the seasons. Sediments and plants lock away organic matter in pulses of decay and renewal.",
      "Tiny swimmers above and recyclers below trade scraps across the mud line. Pelagic grazers and benthic life couple particles and dissolved nutrients at the interface.",
      "On still nights the surface cools, sinks, and briefly stacks warm over cold before wind mixes it again. Thermal inversion redistributes temperature and chemistry through the column.",
      "Lily pads, stems, and roots turn the shallow edge into a maze of cover. Complex macrophytes add surface area and refuge along the littoral.",
      "Predators and prey keep each other's numbers from running away. Linked food-web tiers damp boom–bust cycles so no single layer rules for long.",
      "Cattails and muddy margins blur the line between pond, marsh, and field. Vegetated ecotones catch sediment and host species that move between realms.",
      "Trees lean over the rim, dropping shade, leaves, and perches into the water. Riparian canopy ties the open pond to the wider watershed.",
      "Nitrogen, phosphorus, and carbon trade places through the seasons as storage and release find a rhythm. Biogeochemical cycles settle toward balance across the basin.",
      "Shelter at the bank softens harsh sun and biting wind for everything at the edge. Shade and structure from the rim moderate extremes of heat and exposure.",
      "The pond finally feels whole—stable, layered, and busy through the seasons. At climax the basin behaves as a diverse lentic oasis that largely runs itself.",
    ],
    [
      "First Puddle",
      "Trickle In",
      "Hidden Spring",
      "Kettle Bowl",
      "Rain Pulse",
      "Pond Greens",
      "Water Color",
      "Oxygen Rhythm",
      "Muck Stores Carbon",
      "Mud-Water Trade",
      "Night Mix",
      "Lily Architecture",
      "Food Web Balance",
      "Shoreline Buffer",
      "Overhanging Trees",
      "Seasonal Balance",
      "Sheltered Edge",
      "Summit Basin",
    ],
  ),

  ...buildDoubleTier("sediment", 16, [
    "Brown leaves and dissolved organics drift in from the shore and settle into a carbon-rich fluff along the margin. Allochthonous particles fuel bottom microbes and begin building fertile muck.",
    "Fine silt carries nitrogen that clings to clay grains, tinting the bed pale brown after each rain. Particles slowly release ammonia and nitrate as bacteria rework the mud.",
    "Phosphate sticks to iron oxides in the mud until oxygen drops and algae can pull it back toward the surface. Adsorbed phosphorus shapes how green the open water can turn.",
    "Decaying leaves and pellets stack into a spongy mat where worms tunnel and fungal threads lace through. Organic detritus is the busy nursery layer of the pond bottom.",
    "A thin skin where mud meets water stays oxygenated enough for larvae and nitrifiers to thrive. The interface is where pore water and open water trade nutrients at the surface of the bed.",
    "Tea-dark humic acids stain the sediment and feed bacteria that break stubborn organic polymers. Humic muck chelates metals and holds carbon like a slow sponge.",
    "A few centimeters down, oxygen vanishes and sulfate reducers take over, shaping which roots and animals can persist. Anoxic horizons decide who can live deep in the muck.",
    "Proteins decay in sealed mud until ammonium builds, waiting for a storm or overturn to reach sunlit water. Anaerobic storage feeds the next pulse of algae at the surface.",
    "Nutrients creep through water-filled pores between grains toward roots and surface biofilms. Porewater diffusion shuttles solutes through the bed without a single burrow needed.",
    "Pockets of gravel drain fast and shelter insects between cushions of fine mud that filter every incoming particle. Coarse beds interleave with silt along the littoral.",
    "Tight clay packs into lenses that trap water and phosphorus where plants struggle to root. Glacial clay shapes which margins stay squishy and which hold firm.",
    "Soft mud compresses over seasons, squeezing pore space until water squirts up through worm burrows and cracks. Compaction pushes interstitial water toward the surface film.",
    "Hard rock beneath the basin anchors the shore and bleeds minerals that stain the overlying sediments. Bedrock is the quiet frame the whole bottom rests on.",
    "Silica-rich groundwater seeps along the edge, cementing grains into stable terraces of bottom. Sandstone seeps build rims that resist every storm stir.",
    "Buried ancient soils release stored phosphorus and trace metals as groundwater cuts through below the pond. Deep stores feed the surface when the water column turns over.",
  ]),

  ...buildDoubleTier("fungi", 31, [
    "Fine threads probe fallen leaves and wood, secreting enzymes that free sugars locked in cellulose. Hyphae are the first hands that pull apart tough plant litter on the bottom.",
    "Spores hatch in the water film on fresh detritus before competitors crowd the banquet. Blastocladiomycetes colonize new debris at the shoreline edge.",
    "A creeping slime mold slides across submerged leaves, engulfing bacteria and leaving nutrient-rich trails. Benthic slimes stitch microbial hotspots through the litter.",
    "Tiny chytrids infect algae and pollen in low-oxygen pockets, recycling carbon back into the microbial loop. Even quiet mud pockets buzz with fungal activity.",
    "Mycelium binds leaves into floating rafts that shelter insect larvae at the surface film. Leaf-litter mats are rafts and restaurants at once.",
    "Cup fungi fruit on submerged twigs, releasing spores that seed the next piece of woody debris downstream. Aquatic ascomycetes tie the margin to everything that sinks.",
    "White-rot fungi chew through lignin in drowned stems, freeing nitrogen locked in wood. Wood rot turns branches into food the whole pond can share.",
    "Cottony webs coat dead insects and eggs, returning their tissues to dissolved organics. Saprolegnia turns casualties at the bottom into meals for microbes.",
    "Spores land on the water film atop leaves and sip carbon leaching out of the litter. Ingoldian hyphomycetes live in the same meniscus world ripples know.",
    "Conditioning fungi soften tough fibers so bacteria and shredders can finish the feast. Tough plant armor yields to threads—and then to everyone else.",
    "Fungal and bacterial biofilms coat particles until they stick together and sink like pond snow. Detrital films glue grains into packages filter feeders love.",
    "Flakes of fungal biomass break off and drift, feeding microbes and filter feeders in the water column. Suspended flakes carry the bottom's work into open water.",
    "Proteases split proteins in detritus into amino acids plankton can use right away. Cleavage unlocks nitrogen that was tied up in dead tissue.",
    "Labile carbon bursts from fungal exudates, sparking short-lived bacterial blooms in warm weather. Exudates are sugar gifts that ripple through the food web.",
    "Old fungal communities in deep sediment release nutrients during overturn, as if the bottom exhaled. Primordial plumes feed the surface when the pond mixes.",
  ]),

  ...buildDoubleTier("microbes", 46, [
    "You cannot see them, but the water column hums with bacteria sipping dissolved organics. Free-living heterotrophs respire that carbon and shape the pond's invisible metabolism.",
    "Soft blobs glide over biofilms on stems, swallowing bacteria whole. Amoebas regulate microbial abundance where films thicken on submerged surfaces.",
    "Oval swimmers row with cilia, sweeping bacteria into pellets that sink toward the bottom. Paramecia package microbes into food other animals harvest from the mud.",
    "Tiny bells on stalks snap shut when disturbed, filtering bacteria from passing currents. Vorticella stitch living filters along stems and floating debris.",
    "Green cells turn sunlight into oxygen and sugars in the warm upper water. Chlorella photosynthesizes and exports labile carbon neighbors in the film can use.",
    "One-celled hunters chase bacteria by day and green up when sunlight returns. Euglena mixotrophs bridge grazing and photosynthesis in the same body.",
    "Filaments weave green mats that fix nitrogen other algae can borrow when fertility is low. Cyanobacteria blooms shade the bottom until grazers or wind break them apart.",
    "Golden-brown films coat grains with glassy silica shells that lock carbon when cells die. Diatoms cement sediments and clarify pockets of water as they settle.",
    "Mint-green slicks raft on calm days, shading deeper plants until zooplankton or wind break them apart. Microcystis colonies float as buoyant mats at the surface.",
    "Spinning green spheres roll through warm water, algae sharing sugars with bacterial partners inside. Volvox turns the water column into a carousel of tiny worlds.",
    "Sticky bacterial films glue sediments together and store nutrients between grazing events. Biofilms coat grains and stems—the living veneer sediment and snails depend on.",
    "At night a jostled pond can flash with cold light from dinoflagellate swarms. Bioluminescence marks pulses of microbial abundance in the open water.",
    "Dissolved organics cycle through bacteria and protozoa and back to tiny animals that fish eat. The microbial loop recycles carbon faster than the eye can follow.",
    "Each spring green water blooms, then crashes, feeding bottom bacteria in a seasonal pulse. Phytoplankton peaks couple sunlight to detritus when grazers lag behind.",
    "Archaic lineages in deep mud still breathe chemistry into the water when the pond overturns. Primordial metabolisms shape phosphorus and gases from below.",
  ]),

  ...buildDoubleTier("zooplankton", 61, [
    "Wheel-like mouths spin under a microscope, filtering algae into packages fish larvae snap up. Keratella rotifers turn phytoplankton into animal biomass in warm shallows.",
    "Clouds of tiny animals tint the water ivory after a bloom, grazing green cells by the million. Brachionus swarms convert algae into flesh midwater fish chase.",
    "A sticky foot anchors while a collar net catches particles drifting past. Collotheca filter without roaming, harvesting the pond's suspended pantry.",
    "Hairy backs crawl between grains and submerged leaves, grazing bacterial films in the litter zone. Gastrotrichs link detritus on the bottom to open-water grazers above.",
    "Water fleas pulse through the column, clearing algae surges and leaking nutrients in their wake. Daphnia are the pond's pistons—grazing, reproducing, fueling fish.",
    "Long antennae fan through calm water where fish pressure stays light. Bosmina filter fine particles and thrive when predators keep to deeper cover.",
    "Armored bodies hug the mud, scraping algae from detritus in low-oxygen refuges. Chydorus ties the soft bottom to midwater grazers when blooms fade.",
    "Insects at the surface film snag bacteria and pollen trapped in the meniscus. Scapholeberis hang from above, eating what ripples and wind concentrate there.",
    "Hopping copepods carry lipids up the food web with each jerky stroke through the water column. Cyclops package energy for larger fish one jump at a time.",
    "Larvae hatch in bursts, stitching fish spawning to plankton pulses across the seasons. Nauplii tie reproduction at the rim to feasts in open water.",
    "Slender calanoids commute up at night and down by day, moving carbon between surface and bottom. Diaptomus redistribute nutrients the way weather mixes the pond.",
    "Seed shrimp leave eggs in mud that survive drying and freezing between pond years. Ostracods seed the bottom so plankton can return when water returns.",
    "Phantom larvae rise at dusk to hunt smaller zooplankton under cover of dark. Chaoborus shift predation into the hours when fish eyes struggle.",
    "Grazers lift toward the surface at night and sink by day, shuttling nutrients on a daily schedule. Diel migration pumps carbon through the water column twice over.",
    "Dense clouds turn the pond into a living filter that decides which algae win each season. Zooplankton biomass shapes green water, clear water, and everything between.",
  ]),

  ...buildDoubleTier("aquatic_plants", 76, [
    "Green filaments weave a thin mat on mud and stems until grazers or wind tear it apart. Algae and cyanobacteria fix nitrogen and shade the bottom where light still reaches.",
    "Tiny fronds blanket calm corners, doubling so fast the surface looks paved with green coins. Duckweed skims nutrients from the film and cools the water beneath.",
    "Feathery hornwort drifts without roots, branching through the water column while oxygen bubbles from its leaves. Fry shelter in the forest of stems midwater fish avoid.",
    "Slender seedlings poke through shallow silt, sending first roots that anchor loose sediment against wind chop. Water flax claims the sunlit margin before taller plants arrive.",
    "Underwater meadows spread by runners along the bottom, stems waving in slow currents. Elodea gives fish cover and insects a lattice to climb.",
    "Bristly coontail tufts trap suspended particles and hide larval fish in a green maze. Dense shoots turn open water into a thicket grazers must work through.",
    "Ribbon leaves rise from buried runners, pumping oxygen into the mud with every creeping rhizome. Wild celery ties the soft bottom to the sunlit surface.",
    "Each spring threadlike stems bloom from tubers resting in the mud, then retreat when shade thickens. Sago pondweed pulses with the season—clear water, then quiet dormancy.",
    "Triangular blades and white flowers lift at the margin where pond meets marsh. Arrowhead bridges open water and bank with rooted structure fish nest beside.",
    "Bladders snap shut on microfauna drifting past, returning their nutrients to a plant that never roots in soil. Bladderwort hunts in the water column like a floating trap line.",
    "Oval leaves ride the surface on long stems while rhizomes knit littoral mud against wave wash. Water shield cools the film and steadies the rim where waves chew hardest.",
    "Wide lily pads spread shade below and open pale blooms that draw pollinators to the edge. Fragrant water lilies turn the deep margin into a summer room of scent and shelter.",
    "Floaters, submergents, and emergents stack by depth so light, oxygen, and refuge change step by step. Macrophyte beds make the littoral a layered neighborhood, not a flat lawn.",
    "Sedges and willows shade the rim, dropping leaves that feed the pond while roots hold the bank. A littoral canopy stitches upland forest to open water.",
    "Roots hold sediment, stems cycle nutrients, and the whole shoreline breathes with the seasons. At climax, plants lock into a self-maintaining matrix that runs the margin.",
  ]),

  ...buildDoubleTier("invertebrates", 91, [
    "Snails rasp algae from stones and stems, leaving shiny trails and calcium chips on the bottom. Physids recycle biofilms into food heavier animals can harvest.",
    "Flat ramshorn coils glide through weedy shallows, grazing periphyton and mucus trails bacteria soon colonize. Planorbids turn stem fuzz into fragments midges and fish pick up.",
    "Scuds hop through leaf litter, shredding detritus into pieces the whole bottom can share. Amphipods are the pond's little bulldozers in the litter zone.",
    "Isopods creep along the mud–water line, scavenging dead insects and stirring pore spaces with busy legs. They aerate soft bottom while cleaning what sinks.",
    "Red bloodworms burrow in sediments, pumping water through tubes that link mud and open water. Chironomid larvae move nutrients the way a heartbeat moves blood.",
    "Tiny clams filter silt from the current, clarifying pockets of water and dropping rich pseudofeces. Fingernail clams polish muddy flows into cleaner columns.",
    "Larvae glue pebbles and twigs into portable cases, grazing biofilms while armored against small fish. Caddisflies carry their house along the bottom like stonework nomads.",
    "Silk pads anchor larvae on rocks where flow brings algae to filter. Blackflies stitch the riffle edge to the pond with nets of thread and mouth.",
    "Damselfly nymphs shoot hinged jaws among stems, snatching prey that links plankton to larger hunters. They patrol the plant maze where cover meets hunger.",
    "Water scorpions breathe through tail siphons in still corners, ambushing tadpoles and careless insects. They wait motionless until shadow and vibration say lunch.",
    "Leeches embed in soft muck, then take blood meals when fish and amphibians are common along the shore. Their slow hunts redistribute phosphorus through the litter.",
    "Dragonfly nymphs prowl the substrate in armored masks, controlling snails and midges before emergence. Anisoptera nymphs are the pond floor's patient tigers.",
    "Empty molt shells cling to emergent stems after insects climb to air, weathering chitin and phosphorus back into the littoral. Exuviae are little cliffs of recycled armor.",
    "At dusk thousands of mayflies lift from the surface, exporting bottom production to birds and bats along the bank. Synchronized hatches turn the pond inside out for one hour.",
    "Shredders, grazers, filterers, and predators cycle the floor without any one role running away. At maturity the benthic community regulates itself through the seasons.",
  ]),

  ...buildDoubleTier("small_swimmers", 106, [
    "Tiny fry cling to stems in jelly clumps, living on yolk until jaws harden enough to snap at plankton. Sac fry are the pond's first silver sparks in the weeds.",
    "A gulp of air fills an internal balloon so tiny fish can hover without constant fin work. The swim bladder saves energy in warm shallows where every bite counts.",
    "Weedy nurseries shelter fry from chop and jaws, stems damping waves while parents fan oxygen over nests. Quiet littoral corners are kindergarten for the whole food web.",
    "Silver flashes streak along gravel bars as silversides snap up larvae overhead might miss. Brook silversides link open water to the shoreline in quick, bright passes.",
    "Mudminnows gulp air at the surface and root through soft bottom when oxygen sags in weedy backwaters. They tolerate the muddy rooms larger fish avoid.",
    "Under logs and stones, males polish cavities while females lay eggs on guarded ceilings. Fathead minnows turn debris into nurseries the pond reuses every year.",
    "Schools of dace pick drifting insects in riffle tails, tying open water grazers to shoreline cover. Blacknose dace flash between current and calm in steady shoals.",
    "Barbel fry probe the substrate, sorting edible films from silt in marginal currents. Sensitive whiskers read the bottom long before eyes trust the murk.",
    "Shiners crop algae and zooplankton along the rim, packing energy into flesh bass and herons chase. Common shiners are the pond's busy silver rim runners.",
    "Golden flanks widen the shoal, reflecting light that confuses strikes from above. Brighter shiners ride the safety of numbers through open water.",
    "Fish feel pressure waves along their flanks and dodge jaws before the shadow arrives. The lateral line lets shoals turn as one body in a fraction of a second.",
    "Mimic shiners match the stripe and timing of bolder cousins, hiding in look-alike schools. Copycats trade fame for survival through the open column.",
    "When a shadow crosses the surface, the whole school pivots and density waves ripple through the mass. Shoaling turns many small fish into one moving animal.",
    "At dusk baitfish clouds pulse midwater, drawing herons and bass while redistributing plankton energy. Pelagic shoals couple sunlight algae to top predators.",
    "Minnows and silversides weave plankton production into the midwater metabolism larger fish depend on. A forage matrix tunes who thrives in the open pond.",
  ]),

  ...buildDoubleTier("amphibians", 136, [
    "Gelatinous clutches swell in warm shallows, buoyant rafts anchored to submerged stems until larvae hatch. Egg masses are the pond's first wet constellations each spring.",
    "Feathery gills ruffle from salamander larvae, drawing oxygen straight from the water column. External gills make alien-looking hunters of the open shallows.",
    "Tadpoles graze soft algae from stones and stems, cropping films that would otherwise choke the littoral. Herbivorous larvae clear green fuzz before legs arrive.",
    "Hind limbs bud and lengthen, shifting bodies from swimmers to hoppers along the pond edge. Emergence is the moment the margin fills with awkward new landlings.",
    "Mudpuppies prowl rocky bottoms year-round with feathery gills, hunting insects with cold-water patience. They keep the deep edge alive when ice still lingers.",
    "Bright newts patrol quiet bays, adults returning to water after forest years along the rim. Eastern newts warn with color while they hunt slow prey.",
    "Blue-spotted salamanders slip under leaf litter at the margin, hunting springtails in cool damp roots. They stitch forest floor to pond without ever boasting.",
    "On spring nights spotted salamanders cruise the bottom, bulky bodies stirring sediment and swallowing worms whole. They are the pond floor's polite bulldozers.",
    "Throat sacs balloon under calling males, resonating across the surface and drawing females to defended territories. Vocal sacs turn still evenings into mapped sound.",
    "Spring peepers shrill from flooded shrubs, tiny throats stitching the night chorus that marks the breeding pulse. One peep becomes thousands along the rim.",
    "Leopard frogs sprawl on lily pads, spotted backs warming while tongues lash at flies overhead. Northern leopards bask where sun and prey meet at the surface.",
    "Green frogs sit motionless on banks, larger than peepers and quick to lunge when shadows cross the water. Stillness is their ambush until the strike.",
    "Bullfrogs dominate deep edges with thunderous calls, eating anything smaller that shares the littoral. American bullfrogs set the volume—and appetite—for the whole shoreline.",
    "Frogs and salamanders sip oxygen through damp skin when submerged or sheltering under cover. Cutaneous respiration lets them breathe places gills never could.",
    "Frogs, salamanders, and their larvae couple shoreline hunting to open-water young through the seasons. At climax the pond's amphibian life hums as one saturated chorus.",
  ]),

  ...buildDoubleTier("small_fish", 151, [
    "Circular craters pit the littoral bottom where parents fan fresh water over guarded eggs. Spawning nests concentrate nutrients in swept cups every spring.",
    "Young fish gulp surface air when warm shallows sag, gill covers sealing the chamber between breaths. The operculum buys time in oxygen-thin nurseries.",
    "Fingerlings dart stem to stem, testing jaws on zooplankton and learning the pond's edges one snap at a time. Cover and hunger teach the rim before open water.",
    "Pumpkinseeds patrol sunflecks in the weeds, crushing snails and flashing orange breast plates at rivals. They are the pond's bright-armored weed patrollers.",
    "Bluegills nest in colonies over firm substrate, males sweeping circular beds while females fill guarded cups. Colony spawning turns the bottom into a village of rings.",
    "Green sunfish hold thick cover with bulldog jaws, ambushing prey from root tangles larger cousins avoid. They own the messy rooms under the bank.",
    "Warmouths lurk on twilight bottoms, mottled flanks and a wide mouth ready for crayfish and careless minnows. Stillness ends in a gulp when prey wanders close.",
    "Overlapping scales arm flanks like roof tiles and shed parasites when fish scrape gravel. Ctenoid armor turns every rub into hygiene and protection.",
    "Black crappies suspend over structure, plate-shaped bodies cutting the water column as eyes track passing shoals. They hunt midwater as if hovering in a room of stems.",
    "Rock bass cling to boulders and riprap, red eyes and mottled sides marking a tireless littoral hunter. Hard edges are their territory between weed and stone.",
    "Yellow perch school along the drop-off, barred flanks flashing as the group drifts through weed and open water. The rim shoal links plants to deeper predators.",
    "Dorsal spines lock erect at the first bite, discouraging gape-limited predators and buying seconds to bolt for cover. Spines turn a meal into a painful mistake.",
    "Many bodies bend into one movement when shadows cross, confusing strikes and spreading risk. Schooling cohesion makes sunfish and perch move like a single animal.",
    "Sunfish and perch pack flesh along the rim, exporting invertebrate energy toward bass and herons. A littoral surge fills the shallow band with edible biomass.",
    "Nursery production and top-down control meet in the littoral fish community through the seasons. Small fish tune who thrives along the pond's weedy edge.",
  ]),

  ...buildDoubleTier("reptiles", 169, [
    "A sun-warmed log at the edge is the first hard perch where cold blood can soak heat. Every turtle queue starts with someone claiming the prime basking slot.",
    "The belly shell shields against stones and roots while the carapace above catches light. Plastron and carapace pair armor with the slow metabolism of shoreline hunters.",
    "Ribbon snakes thread through shoreline litter, snapping tadpoles and minnows with quick strikes at the rim. They link open-water prey to the bank in silver flashes.",
    "Painted turtles stack on emergent logs, cropping algae and insects while shells dry between dives into weedy shallows. Log piles become heated apartments above the water.",
    "Musk turtles prowl soft bottom under lily pads, stirring sediment and releasing musk when threatened. They hold muddy territories larger fish skirt around.",
    "Water snakes hunt fish and amphibians along vegetated banks, swallowing meals that tie midwater energy back to shore. Each strike imports open-pond flesh to the rim.",
    "Spotted turtles patrol boggy margins with yellow-spotted shells, picking snails and larvae from stems in cool acidic pockets. They favor the quiet, tea-stained edges.",
    "Growth rings in the shell record seasons of feast and fast, thickening scutes against raccoons and careless heron strikes. Carapace armor deepens with every year survived.",
    "Blanding's turtles cruise shallow wetlands with bright throats, grazing plants and invertebrates while long necks reach into tussocks. They bridge marsh and open water without hurry.",
    "Sandy beaches above the flood line receive leathery eggs, warmth traded against raccoons patrolling the night shore. Nesting sand is the pond's gamble on the next generation.",
    "Snapping turtles lurk in murky bays with dinosaur patience, culling weak ducks and abundant muskrats with bone-shearing jaws. They are the bottom's unhurried enforcers.",
    "Webbed toes and flattened limbs turn legs into paddles between basking perches. Turtles and aquatic snakes cruise without wasting the heat they just collected.",
    "Submerged turtles sip oxygen through vascularized tail vents, stretching dive times while hearts beat slowly below. Cloacal respiration buys hours under lily pads.",
    "When basking hours, diet, and shelter align, digestion and growth hit the sun-powered maximum the pond allows. Thermoregulatory peaks turn warmth into muscle and shell.",
    "Turtles and snakes couple shoreline hunting to open-water foraging through slow radiant metabolism. At climax the pond's reptiles run on sun, patience, and armor.",
  ]),

  ...buildDoubleTier("large_fish", 184, [
    "Predators feel pressure waves along their flanks before eyes catch the motion. The lateral line maps prey and danger through murk where sight fails.",
    "A bubble of gas inside the body fine-tunes hover in midwater without constant fin work. The swim bladder saves energy while fins steer through currents.",
    "At dusk bullheads stir soft bottom, barbels tasting detritus while spines warn casual predators away. Brown bullheads are the pond floor's whiskered night shift.",
    "Catfish roam deeper edges with barbel whiskers and broad jaws, vacuuming invertebrates and scavenging the floor. Channel cats link bottom energy to open water.",
    "Bronze flashes erupt from rocky structure when smallmouth bass ambush crayfish and minnows. They own the hard edges between weed and stone.",
    "Largemouth bass lurk under lily pads and timber, explosive gapes sucking sunfish and frogs from shadows. One strike empties the weedy room.",
    "A forked tail delivers thrust and quick turns through open-water chases. Even lobes on the caudal fin carry predators after fleeing shoals.",
    "Bowfin patrol with ancient jaws and lung-like air breathing, surviving low oxygen while culling abundant small fish. They are living fossils with appetite.",
    "Walleye hunt twilight drop-offs, marble eyes gathering dim light as teeth rake schooling prey. Dusk belongs to the glass-eyed prowlers.",
    "Fine rows of teeth carpet jaws and palates, gripping slippery fish without a fang's gap. Villiform teeth turn every strike into a held meal.",
    "Pike accelerate from weed lines with scissor jaws, trimming midwater biomass in elongated bursts. Northern pike are the pond's green torpedoes.",
    "Gill covers flare in threat and display at structure before strikes or retreats. Opercula signal dominance where cover meets open water.",
    "The food web tilts toward fish eating fish, exporting plankton energy into fewer larger predators. A piscivorous shift concentrates biomass up the chain.",
    "Predators prowl the layer where warm surface water meets cold bottom each season. Thermocline hunts follow the invisible shelf midwater fish feel.",
    "Bass, pike, and catfish couple into a self-regulating midwater community through the seasons. Apex fish tune who survives in the open pond.",
  ]),

  ...buildDoubleTier("waterfowl", 199, [
    "Fluffy down traps air against the skin so ducklings ride cold water without losing heat. Down is the first armor against ice-rimmed shores.",
    "Oil from the tail gland spreads through preening until rain and dives roll off feathers instead of soaking through. Waterproofing turns the surface into a raincoat.",
    "Wood ducks nest in tree cavities above the flood line, dropping to flooded timber and lily edges where acorns fuel broods. They stitch forest canopy to pond margin.",
    "Mallards tip forward in shallows, bills sifting seeds and invertebrates while iridescent specula flash on every commute. Dabbling is the pond's everyday harvest at the rim.",
    "Blue-winged teal arrive early on spring migration, skimming film and mud for protein before pairing in dense cover. They are the first winged pulse after ice-out.",
    "Comb-like edges along the bill strain algae, seeds, and tiny animals from stirred water. Lamellae sieve the pond without swallowing the whole bowl.",
    "Hooded mergansers dive under ice edges for fish and crayfish, serrated bills gripping slippery prey in wooded pockets. They fish where ducks only dabble.",
    "Grebes sink with lobed toes and dense plumage, chasing fish below and building floating nests in cattails. Pied-billed grebes live half under the mirror.",
    "Canada geese graze marsh turf in loud flocks, clipping grass and fertilizing banks with droppings that feed algae and microbes. Honking flocks import and export nutrients along the shore.",
    "Trumpeter swans claim wide open water with deep honks, uprooting plants and demanding long runways from the center. They are the pond's largest winged sculptors.",
    "Webbed toes spread on each power stroke, pushing more water and carrying heavy bodies across the basin. Lobate webbing turns paddling into freight hauling.",
    "Late summer strips flight feathers and grounds birds on safe bays while new plumage grows. Molt trades migration for molting energy on quiet water.",
    "Ancient routes link this pond to distant wetlands, delivering seasonal grazers and filterers along the flyway. Migration is the pond's long-distance nutrient courier.",
    "Guano from roosts concentrates nitrogen and phosphorus on banks and shallows in predictable rings. Droppings fertilize periphyton where birds loaf and sleep.",
    "Ducks, geese, grebes, and swans couple shoreline grazing to open-water foraging through the seasons. At climax winged life tunes the pond's nutrient metabolism from above.",
  ]),

  ...buildDoubleTier("shore_mammals", 214, [
    "Outer guard hairs shed water and mud so dense underfur stays dry along the saturated rim. Small mammals tunnel, swim, and forage where bank meets pond.",
    "Fleshy rays on a star-shaped nose taste bottom in black water, pinpointing worms faster than eyes could in root-choked shallows. The star-nosed mole reads the mud by touch.",
    "Water shrews hunt along the surface film with frantic metabolism, diving for aquatic insects. They stitch open-water energy into the litter layer at the edge.",
    "Meadow voles graze sedges and clip runways through dense turf, cycling plants into tunnels where owls, snakes, and mink listen for rustles. The bank hums with hidden traffic.",
    "Muskrat dens burrow into banks with chambers above flood lines, storing cattail stems and opening channels that oxygenate stagnant backwaters. Burrows are pantries and plumbing at once.",
    "Muskrats push lodge mounds from cattails and mud, grazing rhizomes and fertilizing edges where paths meet waterfowl loafing zones. Lodges turn plants into architecture.",
    "Mink thread shorelines with sinuous bodies, diving after frogs and fish and leaving scent posts along hunting corridors. They are the rim's quick, fierce weasel.",
    "Webbed hind feet power muskrats and beaver through channels, each kick throwing turbid water toward filter feeders. Every stroke stirs nutrients off the bottom.",
    "Raccoons wash food at the pond edge under moonlight, nimble paws sorting crayfish while tracks lace mud around muskrat runs. Washing is dinner and detective work.",
    "River otters slide down muddy banks, chasing fish through weedy bays where beaver flow slows pursuit. Play and hunger share the same splash.",
    "Beaver canals cut straight channels through marsh, lowering water behind dams and spreading shallow habitat for waders and grazers. Engineering reshapes who can use the rim.",
    "Beaver dams stack sticks and mud across outlets, backing up water, trapping sediment, and drowning forests into standing snags. Dams are the pond's rude thermostat.",
    "Lodges rise as domes of branches plastered with mud, winter pantries stocked with bark while underwater entrances dodge most predators. Warm rooms sit inside cold water.",
    "Beaver and hare clip willows and alders, resetting shrub height so light reaches the water's edge again. Browsing pressure opens the shoreline like pruning shears.",
    "Voles, muskrats, mink, raccoons, otters, and beaver couple burrowing to dam-building through the seasons. At climax shoreline mammals engineer the pond's rim.",
  ]),

  ...buildDoubleTier("hunting_birds", 229, [
    "Fine powder frays from feathers during preening until mist and splash roll off dry flight plumage. Powder down is the raincoat behind every dive.",
    "Green herons stalk from low branches and lily pads, coiled necks striking minnows and frogs in still shallows. They fish like patience with a dagger bill.",
    "Kingfishers rattle over open water, hovering before dives that hammer small fish against perches. Belted rattles mark every successful splash.",
    "Great blue herons wade with patient strides, spearing fish and amphibians that export open-water biomass to shore. Slow feet, fast bill—classic pond hunting.",
    "Caspian terns plunge from height with orange bills, carrying surface fish to sandbars and shrieking colonies. Commute lines ring the pond at dawn.",
    "A third eyelid slides across the eye underwater so herons and kingfishers watch prey through green-tinted light. The nictitating membrane protects vision in the splash.",
    "Comb-like claws grip slippery perches and muddy banks when wet feet would slide. Pectinate toes anchor the strike at the moment of the jab.",
    "Night herons hunt at dusk in hunched postures, gulping fish and crayfish while day waders roost nearby. The pond's second shift begins when color drains from the sky.",
    "Northern harriers quarter low over marsh with owl-like faces, hearing voles in grass. They link upland meadows to open margins in silent passes.",
    "Barbed pads on osprey feet grip writhing fish during the climb from splash to nest. Spicules lock catches while wings still drip.",
    "Osprey circle high before feet-first plunges, carrying trout and panfish to stick nests where fish bones litter the ground below. Snags become pantries in the sky.",
    "Bald eagles pirate catches and patrol shorelines, pulling energy from fish, waterfowl, and carrion. They sit at the top aerial tier with borrowed and earned meals.",
    "Forward vision doubles so raptors and fish-hawks pick ripples across the whole basin from one dead snag. Binocular acuity turns a perch into a radar dish.",
    "Nest colonies pack islands and drowned timber, concentrating guano, noise, and predation that reshapes fish below. Rookery expansion makes the shoreline loud and hungry.",
    "Herons, kingfishers, terns, harriers, osprey, and eagles couple wading strikes to aerial piracy through the seasons. Hunting birds tune the pond from above and at the rim.",
  ]),

  ...buildDoubleTier("great_mammals", 244, [
    "Each spring velvet antlers shed in strips of fuzzy skin, littering trails with calcium snails and mice recycle along the rim. The pond gets a brief gift of bone meal from the deer woods.",
    "Lawn and edge habitat wake at dawn and dusk when deer and fox move between forest and open water in predictable pulses. The crepuscular yard is busiest when humans are still indoors.",
    "White-tailed deer browse willow and jewelweed, clipping bank vegetation and leaving hoof-packed paths that channel runoff toward the inlet. Their trails are the shoreline's soft engineering.",
    "Hooves firm muddy approaches, squeezing pore space in bank soils where wallows and tracks overlap. Ungulate compression concentrates nutrients where great animals stand often.",
    "Coyotes patrol scent lines at dawn, yipping across frozen bays and culling weak waterfowl and rodents. They tie upland fields to the pond in sharp, vocal circuits.",
    "Bobcats stalk from cedar thickets with silent pads, ambushing rabbits and birds where forest shade meets emergent marsh. The ecotone is their doorway between worlds.",
    "Dense underfur traps air against skin through winter while ice rims the shore and wind strips open water. Bears and deer thermoregulate through months the pond wears white.",
    "Black bears rake ant hills and tear rotting logs at the edge, importing forest calories and scarifying litter where amphibians hide. Bear work opens new rooms in the leaf pack.",
    "Wide palmate antlers shovel aquatic plants and widen trails through shallows each autumn rut. Moose kin turn submerged greens into trampled harvest lanes.",
    "Great bodies churn soft marsh into muddy wallows, aerating rhizomes and releasing phosphorus while heat eases at midday. Sedge wallows are bathtubs that fertilize the margin.",
    "Moose wade chest-deep for lily pads and twigs, the largest browser stripping shoots that would choke open water. Eastern moose make the pond feel small when they rise from the lilies.",
    "Pollen and bone whisper that mastodons once bulldozed similar shores at continental scale. Prehistoric megafauna imported browse and wallow nutrients long before today's deer paths.",
    "Braided trails link ridge, shore, and inlet, moving scat, seeds, and compaction around the watershed rim. Game trail networks are highways written in mud.",
    "Urine, hair, and dung pulse onto banks when herds drink at dusk, fertilizing shoreline algae and soil microbes. Megafauna nutrients arrive in packages larger fish never carry.",
    "Deer, predators, bears, and moose couple browsing to wallowing through the seasons. At climax large mammals tune the pond's rim metabolism with hoof, appetite, and wallow.",
  ]),

  ...buildDoubleTier("humans", 259, [
    "Sapling and bark frames rise at the shore, shelter keeping fire and story near the water without closing the pond to wind and wildlife. A wigwam turns the margin into home.",
    "Birchbark canoes slip along the littoral, poling through lily beds and carrying harvest, trade, and quiet observation across the basin. Each stroke links shore to shore without breaking the surface calm.",
    "Late summer bends wild rice stems into canoes, knocking grain into the hull while roots stay to regrow next year. Harvest is a rhythm that feeds people and leaves the shallows intact.",
    "Black ash splints weave baskets for fish and rice, split along growth rings in craft that ties floodplain trees to daily pond life. Baskets carry the forest to the water's edge.",
    "A voyageur outpost lands trade goods and metal tools where portages meet open water, linking the pond to distant markets. Canoes anchor where routes converge and stories swap.",
    "Crosscut saws ring through cedar and pine, felling trees for docks, cabins, and cordwood while opening light gaps along the bank. Each cut reshapes shade at the rim.",
    "Cleared fields and stone cellars claim homestead ground, fencing livestock and planting crops whose runoff and manure reach the inlet after rain. The watershed learns new edges.",
    "Straight ditches pull water off fields, lowering groundwater and sending sediment pulses into the pond each spring thaw. Drainage trades flooded acres for muddy inflows.",
    "Afternoon light catches stained glass in village windows where the pond becomes backdrop to settled craft, not only food. Art arrives when the shore has time to look outward.",
    "Split-bamboo rods arc over rises while anglers read currents and hatching insects, catch-and-release leaving fish biomass in the water. Fly fishing is watching made into sport.",
    "Cedar decoys float in rigged lines, shaping hunter pressure and training eyes to read wind, cover, and open lanes on the surface. Decoys teach what ducks might choose.",
    "Timber piers extend into deeper water, concentrating foot traffic, boat wakes, and creosote at the pond's most visited edge. The pier is where human weight meets the basin.",
    "Storm basins hold runoff from roofs and pavement, settling grit and nutrients before overflow slips toward the same water people fish. Engineering tries to catch rain before the pond does.",
    "Secchi disks, plankton nets, and maps turn the pond into data that guides management. Limnological surveys name what swimmers and fish already feel in season.",
    "Indigenous harvest, settler land use, recreation, and science meet on one shoreline where decisions set the pond's future. At climax human care and appetite write the next chapter together.",
  ]),

  ...buildDoubleTier("cryptids", 274, [
    "Flashlight beams catch green glow at the far shore—deer, raccoon, or something that will not stay in the field guide. Eye shine turns every night walk into a maybe.",
    "Camp stories tell of round heads rocking above the reeds after midnight, wakes too wide for a beaver. Melon-headed silhouettes live where testimony outruns taxonomy.",
    "At dawn, long strides appear in damp sand where no one admits to walking after dark. Night marcher tracks are questions pressed into the margin.",
    "Cougar screams meet impossible geometry in wampus cat tales, clawless scrapes on dock posts, dogs that refuse the marsh trail. Fear learns new shapes at the pond rim.",
    "Shoulder-height prints stack beside the inlet with bipedal spacing that sends anglers home early. Dogman reports make locks worth checking twice.",
    "Fog erases the tree line and shapes shift between cedars along old portage routes. Loup-garou whispers follow French-Canadian trails into modern campfires.",
    "Broken tops and snapped saplings blame wind that never blew that night in logging country. Agropelter legends hang on branch-swinging imps just out of sight.",
    "Firewood stacks fall and fish stringers vanish always just beyond peripheral vision. Hidebehind lore explains the pond rim's small, maddening thefts.",
    "A hoax headline once claimed a lake monster at the county line; retraction never erased the bumper stickers or August boat traffic. Stories outlive facts at the bait shop.",
    "Serpent humps roll through chop on smaller waters, camera phones turning wakes into shared, unverified proof. Bay tales migrate inland with every retelling.",
    "Under ice, dreams of Mishipeshu—the copper-backed panther—warn that the pond demands respect when nets or mines take too much. Teaching spirits guard more than fish.",
    "Wendigo stories thread hunger and winter isolation into caution about extraction pushed past what shoreline communities can sustain. Metaphor wears fur in the north woods.",
    "On still mornings cotton-thick fog rolls off the basin until pier lights look farther than they are and sounds carry wrong. Ectoplasmic haze is weather with mood.",
    "Every anecdote at the bait shop layers fear, wonder, and place-names until the pond wears a second map made of story. Folklore density thickens with free coffee and long pauses.",
    "Eye shine, regional monsters, hoaxes, and teaching spirits meet at the margin where mystery keeps the ecosystem narratively alive. The bait-shop ledger is the true field guide.",
  ]),

  ...buildDoubleTier("spirits", 289, [
    "Cool flames drift above wet meadow and bog, luring travelers toward open water while methane and folklore share the same glow. Will-o'-the-wisps are marsh gas wearing an old name.",
    "Blue sheets of light hang over seeps at dusk where decomposition meets air and old timers call it foolish fire. Ignis fatuus dances where the bog exhales.",
    "Owl cries, loon wails, and human shouts return from cliff and tree until direction itself feels uncertain. The pond echo repeats what you wish you had not called.",
    "Shapes flicker at the corner of vision—motion without ripples—thickening when mist erases the far shore. Phantasms live where the eye finishes the story alone.",
    "Paddlers who drowned or disappeared still sound in song and splash where portage meets still water. Voyageur ghosts walk trails in memory, not on maps.",
    "A pale figure glides at moonrise in shoreline legend, warning of drownings, ice, and depth that does not forgive. The white lady is caution dressed as light.",
    "Sudden chill hits when warm surface water slides over spring-fed bottom near drowned timber. Wraiths cling to cold inlets you feel before you name.",
    "Stones skip at night, lids lift, splashes come with no thrower—racket that keeps docks and cabins nervously alive. Poltergeist mischief owns the hour after sunset.",
    "Old oaks and red maples at the rim carry spirit-of-place stories tying canopy shade, leaf fall, and acorn rain to the littoral. Dryads are the forest's attention at the bank.",
    "Spring seeps and outlet riffles host guardians in tales that caution against blocking channels or fouling headwater pools. Naiads move where flow is born.",
    "Seasons of ice, bloom, fish rise, and human care accrue until the pond feels watched and named. Genius loci is the personality of water that knows you back.",
    "Doubled silhouettes pass through fog without disturbing ripples, vanishing when boats enter the lane they seemed to occupy. Spectres prefer the moment before proof.",
    "On still nights starlight and moonpath reflect so perfectly the sky seems to trade places with the water. Astral convergence is the pond holding its breath with the stars.",
    "Depth, cold, and silence feel deeper than bathymetry maps admit—threshold water legends place between worlds. A dimensional rift is the place maps end and stories begin.",
    "Marsh lights, drowned voices, place spirits, and sky-mirror omens steer mood and myth through the unseen layer of the basin. Thin places are where the pond listens hardest.",
  ]),

  ...buildDoubleTier("leviathans", 304, [
    "Whiskered sturgeon nose through soft bottom, armored plates glinting as slow growth ties deep basin energy to rivers upstream. Lake sturgeon make the pond floor feel ancient and deliberate.",
    "Long-jawed gar cruise weed lines, ganoid scales flashing when ambush strikes erupt from shallow cover. Alligator gar remind smaller fish that shadows can bite.",
    "In story and deep water, giant isopods scavenge the floor like roly-poly continents, recycling carrion where light fades to green-black. The bottom has its own heavy cleaners.",
    "Coelacanth shadows linger in memory—lobed fins, blue flesh—proof the deepest bowl can hold lineages thought extinct for millions of years. Living fossils still patrol the cold logic below.",
    "Devonian dream brings armored plating and shearing jaws that turn the food web into sudden, bone-crushing redistribution. Dunkleosteus is hunger cast in stone.",
    "Long necks thread through legend and loch tales, bodies turning ripples into questions about what a kettle pond hides below the thermocline. Plesiosaurs own the mystery line.",
    "Mosasaur thrust rules the water column in story—apex hunters that collapse schools into fewer, larger bodies with each pass. Mesozoic appetite still echoes in deep imagination.",
    "Spiraling whorls of teeth shred the idea of a gentle bottom into rotating, prehistoric hunger. Helicoprion is the buzz-saw jaw you never want to meet in murk.",
    "Arms uncoil in abyssal myth, chromatophores flashing in black water where the deepest bowl feels oceanic. Giant squid turn the pond's floor into ink and question marks.",
    "Clicks echo through darkness toward squid and canyon walls in story as much as sea. Sperm whale scale drags open-water drama into the basin's heaviest dreams.",
    "Megatooth shadows make every large wake a reminder of what apex meant before ice and time. Teeth still wash ashore in dreams if not in nets.",
    "Blue whale mass filters the smallest prey at the largest scale, heartbeats and flukes translating plankton into a body larger than the dock. Size itself becomes a way of eating.",
    "Kraken tentacles knot ships and folklore, storm surfacing and ink trading fear for awe at the inlet. The surface remembers when something vast pulled back.",
    "In Norse telling Jörmungandr encircles the world so that when it stirs, tides and pond seiches feel like the same breath. Serpent scale turns the whole basin into one held exhale.",
    "Sturgeon, gar, living fossils, and mythic leviathans couple into one deep-water metabolism that owns the pond's heaviest stories. Depth's crown is weight, memory, and appetite below the thermocline.",
  ]),

  ...buildDoubleTier("abyssals", 319, [
    "Endless flakes of dead plankton and pellets drift down through dark water, snowing nutrients to bottom life. Marine snow is the pond's quiet blizzard below the last sun.",
    "Hagfish knot themselves in slime and rasp carcasses from the floor, turning whale-fall energy into soft-bodied recycling. They are the mop crew of the cold deep.",
    "Tripod fish perch on stiff fin rays, mouths open to whatever the current delivers in patient, energy-starved posture. Waiting is the hunting strategy where food is rare.",
    "The vampire squid turns its cape inward in threat, living on marine snow and detritus where oxygen thins and predators fade. It survives by eating what sinks and vanishing when cornered.",
    "Blue-green sparks flash in black water, counterillumination rewriting who can see whom below the last photon. Luciferin light is the grammar of deep conversation.",
    "A glowing lure dangles ahead of unhinging jaws that swallow prey whole in cold ambush logic. Anglerfish turn darkness into bait and sudden dinner.",
    "Gulper eels balloon their throats around meals larger than the body, storing scarce calories from sporadic passes through the abyss. One gulp can last a long hunger.",
    "Black dragonfish flash needle teeth and red light most prey never see—a private wavelength of hunting. They strike in a color the surface world forgot.",
    "Hot, mineral-rich water bleeds from chimneys where chemistry replaces sunlight as the primary gift. Hydrothermal vents are suns made of sulfur and pressure.",
    "Bacteria fix carbon from hydrogen sulfide at vents and seeps, farming a food web without photosynthesis. Chemosynthesis is life eating stone breath.",
    "Pale columns of tube worms grow around vents, plumes trading symbionts for a life tied to volcanic breath. Giants rise where the bottom exhales heat.",
    "Gelatinous snailfish ghost across hadal trenches, pressure-adapted bodies proving life persists where charts go deepest. The Mariana spirit is softness that survives crushing dark.",
    "Pressure, cold, and darkness compress the lowest bowl into a point of absolute patience. The void singularity is metaphor for hunger that outwaits season.",
    "Light, warmth, and season no longer reach—only sediment rain and slow hunger remain past the threshold. The event horizon is where the pond forgets the sky.",
    "Marine snow, vent chemistry, bioluminescent hunters, and hadal extremes couple into one bottom metabolism without sun. Hadal throne is the pond's rule in crushing, patient dark.",
  ]),

  ...buildDoubleTier("celestials", 334, [
    "Fronts and pressure cells decide when rain fills the pond and when wind mixes the surface. Weather wheels turn above the watershed before the first ripple answers.",
    "Sunbeams spear through cloud gaps at dawn and dusk, striping the water and pulling insects and fish into brief golden feeding windows. Crepuscular rays are the pond's spotlight hours.",
    "Electric blue clouds shine after sunset, ice crystals catching summer light while the pond below already holds night. Noctilucent shine is sky refusing to go dark.",
    "At solar zenith the sun rides its highest arc, shortest shadows at noon when heating peaks and algae photosynthesis races the clock. High noon is the pond's busiest photosynthesis hour.",
    "Midday twilight falls when the moon crosses the sun, temperature and behavior pausing as if the basin forgot which season owns the sky. Eclipse hush is a breath held across the whole water.",
    "A close moon swells tides in connected waters and tightens pull on groundwater until shorelines breathe with seiche. Lunar perigee makes the rim rise and fall like a slow chest.",
    "Earth's magnetic shield bends solar wind away while migration compasses still run true north. The magnetosphere is the pond's invisible roof against auroral storms.",
    "Green and red curtains drift over northern horizons, charged particles painting sky that reflects faintly on still, dark water. Aurora borealis is weather made of light.",
    "August nights streak with meteors dissolving in upper air while watchers on the dock count falls mirrored in black glass. The Perseid radiant turns the sky into falling punctuation.",
    "In story twin suns warm two dawns and stretch the pond's daylit metabolism across a mythic horizon. Binary light is appetite doubled at the surface.",
    "Telescope haze and tale recall birth clouds of suns, reminding the basin it swims in a galaxy of dust and ignition. Stellar nebula is the pond's family photo at cosmic scale.",
    "Supernova remnants seed space with heavy elements—calcium and iron in bone and shell trace back to a star that outshone the whole pond for a day. You are drinking old fire.",
    "Radio-sky lighthouses tick with spins so precise they feel like clocks for seasons older than ice scouring this kettle. Pulsar beacons mark time deeper than trees.",
    "In teaching metaphor folded spacetime mirrors depth on the water—a cosmos where even light cannot climb out. The event horizon is sky answering the pond's deepest bowl.",
    "Weather, moon, aurora, meteors, and stellar scale link sky to water until light, tide, and myth move together. Sky mirror is the pond holding heaven on its skin.",
  ]),

  ...buildDoubleTier("transcendence", 349, [
    "Awareness flickers across ripples, roots, and deep water where every denizen tier already hums. The pond begins to notice itself.",
    "Impulse moves without sound through anglers, herons, and microbes like signals in a quiet network. Telepathic conduction is the basin thinking in parallel.",
    "Schools, flocks, and biofilms move as if the whole pond breathes on one schedule. Collective consciousness gathers many lives into a single rhythm.",
    "Human story, science, and myth fold into living memory, culture sitting atop ecology like a second weather over the water. The noosphere is the pond remembered aloud.",
    "Hours at the dock stretch while seasons compress where depth holds stillness. Spacetime distortion is patience bent at the shore.",
    "Ice-off and bloom replay in metaphor until the system learns each turn by heart. A temporal loop is the same dragonfly season returning until it sticks.",
    "Identity persists whether water rises, falls, or freezes to white stone. A fourth-dimensional anchor is shape that outlasts every drawdown.",
    "Awareness traces inlet, outlet, and night migration across the watershed without a body in the way. Astral projection is sight that swims the whole basin.",
    "Care and neglect write themselves on clarity, weeds, and fish behavior as if ideas weighed mass. Thought-forms turn attention into consequence you can see.",
    "Trophic links, place-names, and family ponds persist when single lives end. Conceptual immortality is pattern outliving any one swimmer or steward.",
    "Action at one bank echoes in chemistry at the other without a visible wire. Entangled shores couple distant margins in quiet quantum metaphor.",
    "Sun to plant to fish to soil—each exchange a soft alchemy that keeps the whole from stalling. Etheric transmutation shifts energy between layers without waste.",
    "Rain, groundwater, and sky feel born from the basin rather than visiting it. Reality genesis is the pond as a self-sustaining world with soft borders.",
    "No empty niche remains; biomass and story pack until the water reads as one saturated organism. Omnipresent saturation is every tier speaking at once.",
    "Mud, open water, sky, myth, and abyss breathe as one whole that no longer behaves like a puddle. One whole pond is transcendence—the basin knowing its name.",
  ]),
];

function buildDoubleTier(
  denizenId: string,
  startId: number,
  ecologyNotes: readonly string[],
): SpecialtyDef[] {
  const def = getDenizenDef(denizenId);
  if (!def) return [];
  const fallbackLabel = def.name;
  const namesByTier: Record<string, readonly string[]> = {
    sediment: [
      "Leaf Litter",
      "Nitrogen Silt",
      "Phosphorus Mud",
      "Detritus Mat",
      "Mud Surface",
      "Dark Muck",
      "Oxygen-Free Deep",
      "Buried Ammonia",
      "Mud Channels",
      "Gravel Pockets",
      "Clay Lenses",
      "Squeezed Mud",
      "Hard Shore",
      "Sandstone Seep",
      "Ancient Store",
    ],
    fungi: [
      "Hyphae Spread",
      "Spore Hatch",
      "Creeping Slime",
      "Pond Chytrids",
      "Leaf Raft",
      "Twig Fruiting",
      "Wood Rot",
      "Egg Web",
      "Film Spores",
      "Softening Fibers",
      "Sticky Film",
      "Floating Flakes",
      "Protein Unlock",
      "Carbon Burst",
      "Deep Fungal Pulse",
    ],
    microbes: [
      "Water Bacteria",
      "Blob Hunter",
      "Cilia Sweep",
      "Stalk Filter",
      "Sunlit Algae",
      "Day-Night Hunter",
      "Nitrogen Fixers",
      "Diatom Coat",
      "Green Slick",
      "Spinning Colony",
      "Living Biofilm",
      "Night Spark",
      "Nutrient Loop",
      "Spring Bloom",
      "Deep Microbes",
    ],
    zooplankton: [
      "Spinning Filter",
      "Rotifer Cloud",
      "Collar Feeder",
      "Leaf Crawler",
      "Water Flea Pulse",
      "Filter Antennae",
      "Bottom Scraper",
      "Surface Hanger",
      "Copepod Hop",
      "Larva Burst",
      "Vertical Commute",
      "Seed Shrimp",
      "Phantom Hunter",
      "Night Rise",
      "Living Filter",
    ],
    aquatic_plants: [
      "Green Surface Mat",
      "Duckweed Blanket",
      "Floating Hornwort",
      "Shore Seedling",
      "Underwater Meadow",
      "Coontail Thicket",
      "Ribbon Leaves",
      "Spring Sprouts",
      "Arrowhead Margin",
      "Bladder Traps",
      "Oval Pads",
      "Lily Room",
      "Layered Shore",
      "Overhanging Rim",
      "Rooted Kingdom",
    ],
    invertebrates: [
      "Pond Snail",
      "Ramshorn Snail",
      "Scud Hopper",
      "Bottom Crawler",
      "Bloodworm Burrow",
      "Fingernail Clam",
      "Pebble Case",
      "Riffle Filter",
      "Damselfly Nymph",
      "Water Scorpion",
      "Leeches",
      "Dragonfly Nymph",
      "Molt Shells",
      "Mayfly Hatch",
      "Living Bottom",
    ],
    small_swimmers: [
      "Yolk Fry",
      "Float at Depth",
      "Quiet Nursery",
      "Brook Silverside",
      "Central Mudminnow",
      "Fathead Minnow",
      "Blacknose Dace",
      "Barbel Fry",
      "Common Shiner",
      "Golden Shiner",
      "Pressure Sense",
      "Mimic Shiner",
      "School Turn",
      "Dusk Cloud",
      "Forage Shoal",
    ],
    amphibians: [
      "Egg Raft",
      "Feather Gills",
      "Algae Grazer",
      "Leg Buds",
      "Mudpuppy",
      "Eastern Newt",
      "Blue-Spotted Salamander",
      "Spotted Salamander",
      "Throat Drum",
      "Spring Peeper",
      "Leopard Frog",
      "Green Frog",
      "American Bullfrog",
      "Skin Breath",
      "Pond Chorus",
    ],
    small_fish: [
      "Nest Crater",
      "Gill Cover",
      "Fingerling",
      "Pumpkinseed",
      "Bluegill",
      "Green Sunfish",
      "Warmouth",
      "Scale Armor",
      "Black Crappie",
      "Rock Bass",
      "Yellow Perch",
      "Spine Shield",
      "Sunfish School",
      "Rim Surge",
      "Weedbed Crown",
    ],
    reptiles: [
      "Basking Log",
      "Belly Shell",
      "Ribbon Snake",
      "Painted Turtle",
      "Musk Turtle",
      "Water Snake",
      "Spotted Turtle",
      "Shell Rings",
      "Blandings Turtle",
      "Sandy Nest Beach",
      "Snapping Turtle",
      "Webbed Paddles",
      "Tail Vent Breath",
      "Basking Peak",
      "Basking Empire",
    ],
    large_fish: [
      "Pressure Line",
      "Midwater Float",
      "Brown Bullhead",
      "Channel Catfish",
      "Smallmouth Bass",
      "Largemouth Bass",
      "Forked Tail",
      "Bowfin",
      "Walleye",
      "Gripper Teeth",
      "Northern Pike",
      "Gill Flare",
      "Fish-Eat-Fish",
      "Layer Hunt",
      "Midwater Tyrant",
    ],
    waterfowl: [
      "Down Warmth",
      "Preen Oil",
      "Wood Duck",
      "Mallard",
      "Blue-Winged Teal",
      "Bill Sieve",
      "Hooded Merganser",
      "Pied-Billed Grebe",
      "Canada Goose",
      "Trumpeter Swan",
      "Webbed Stroke",
      "Summer Molt",
      "Migration Path",
      "Roost Fertilizer",
      "Feathered Dominion",
    ],
    shore_mammals: [
      "Waterproof Coat",
      "Star-Nosed Mole",
      "Water Shrew",
      "Meadow Vole",
      "Muskrat Den",
      "Muskrat Lodge",
      "Mink",
      "Webbed Kick",
      "Raccoon",
      "River Otter",
      "Beaver Canal",
      "Beaver Dam",
      "Beaver Lodge",
      "Willow Browse",
      "Shore Engineer",
    ],
    hunting_birds: [
      "Feather Powder",
      "Green Heron",
      "Belted Kingfisher",
      "Great Blue Heron",
      "Caspian Tern",
      "Underwater Eyelid",
      "Gripper Claw",
      "Night Heron",
      "Northern Harrier",
      "Fish-Grip Feet",
      "Osprey",
      "Bald Eagle",
      "Sharp Sight",
      "Nest Colony",
      "Strike From Above",
    ],
    great_mammals: [
      "Antler Velvet",
      "Dawn-Dusk Yard",
      "White-Tailed Deer",
      "Hoof-Packed Bank",
      "Coyote",
      "Bobcat",
      "Winter Underfur",
      "Black Bear",
      "Shovel Antlers",
      "Marsh Wallow",
      "Eastern Moose",
      "Mastodon Memory",
      "Braided Trails",
      "Herd Fertilizer",
      "Trail Kings",
    ],
    humans: [
      "Shore Wigwam",
      "Birchbark Canoe",
      "Wild Rice Harvest",
      "Black Ash Basket",
      "Voyageur Outpost",
      "Crosscut Saw",
      "Homestead Clearing",
      "Drainage Ditch",
      "Village Studio",
      "Fly Rod",
      "Duck Decoy",
      "Timber Pier",
      "Storm Basin",
      "Pond Survey",
      "Watershed Testament",
    ],
    cryptids: [
      "Flashlight Eyes",
      "Melon Head",
      "Dawn Tracks",
      "Wampus Cat",
      "Dogman",
      "Rougarou Trail",
      "Agropelter",
      "Hidebehind",
      "Lake Monster Hoax",
      "Inland Serpent",
      "Mishipeshu",
      "Wendigo Warning",
      "Morning Fog",
      "Bait-Shop Stories",
      "Bait-Shop Legend",
    ],
    spirits: [
      "Marsh Lights",
      "Foolish Fire",
      "Pond Echo",
      "Corner of Eye",
      "Voyageur Ghost",
      "White Lady",
      "Wraith",
      "Poltergeist",
      "Dryad",
      "Naiad",
      "Pond Watcher",
      "Fog Walker",
      "Star on Water",
      "Between Worlds",
      "Thin Places",
    ],
    leviathans: [
      "Lake Sturgeon",
      "Alligator Gar",
      "Deep Scavenger",
      "Coelacanth",
      "Devonian Jaws",
      "Plesiosaur",
      "Mosasaur",
      "Buzz-Saw Jaws",
      "Giant Squid",
      "Sperm Whale",
      "Megalodon",
      "Blue Whale",
      "Kraken",
      "World Serpent",
      "Depth's Crown",
    ],
    abyssals: [
      "Marine Snow",
      "Hagfish",
      "Tripod Fish",
      "Vampire Squid",
      "Blue Spark",
      "Lure Light",
      "Gulper Eel",
      "Black Dragonfish",
      "Hydrothermal Vent",
      "Vent Bacteria",
      "Giant Tube Worm",
      "Hadal Ghost",
      "Crushing Dark",
      "Last Light",
      "Hadal Throne",
    ],
    celestials: [
      "Weather Wheel",
      "Sunbeams",
      "Night-Shining Cloud",
      "High Noon Sun",
      "Solar Eclipse",
      "Close Moon",
      "Aurora Shield",
      "Aurora Borealis",
      "August Meteors",
      "Twin Suns",
      "Star Nursery",
      "Supernova Remnant",
      "Sky Lighthouse",
      "Folded Sky",
      "Sky Mirror",
    ],
    transcendence: [
      "Pond Wakes Up",
      "Silent Network",
      "One Breath",
      "Living Memory",
      "Bent Time",
      "Season Replay",
      "Lasting Shape",
      "Watershed Sight",
      "Care Made Visible",
      "Patterns That Stay",
      "Entangled Shores",
      "Soft Alchemy",
      "Self-Made World",
      "Every Niche Full",
      "One Whole Pond",
    ],
  };
  const names = namesByTier[denizenId] ?? [];
  return UNLOCK_TIER.map((unlock, i) =>
    doubleDenizen(
      startId + i,
      names[i] ?? `${fallbackLabel} ${i + 1}`,
      denizenId,
      unlock,
      specialtyCatalogPrice(startId + i),
      ecologyNotes[i] ?? `${fallbackLabel} ecology note.`,
    ),
  );
}

export const SPECIALTY_IDS = new Set(SPECIALTIES.map((s) => s.id));

export function getSpecialtyDef(id: number): SpecialtyDef | undefined {
  return SPECIALTIES.find((s) => s.id === id);
}

export function specialtiesForDenizen(denizenId: string): SpecialtyDef[] {
  return SPECIALTIES.filter((s) => s.denizenId === denizenId);
}

/** Shop grid: lowest price first (pond production mixed with other evolutions). */
export function compareVisibleSpecialtyShopOrder(
  a: SpecialtyDef,
  b: SpecialtyDef,
): number {
  if (a.price !== b.price) return a.price - b.price;
  return a.id - b.id;
}

/** Zero-based tier index (0–14) within the denizen's fifteen specialties. */
export function specialtyTierIndex(def: SpecialtyDef): number {
  const idx = specialtiesForDenizen(def.denizenId).findIndex((s) => s.id === def.id);
  return idx >= 0 ? idx : 0;
}
