# Generated by Django 6.0.3 on 2026-04-04 21:48

import django.db.models.deletion
import qff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grid_width', models.PositiveSmallIntegerField(default=3)),
                ('grid_height', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('search_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='qff.area')),
            ],
            options={
                'ordering': ['area_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[qff.models.validate_character_name])),
                ('name_normalized', models.CharField(db_index=True, max_length=20, unique=True)),
                ('last_activity_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qff_character', to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='qff.characterclass')),
                ('current_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupants', to='qff.room')),
            ],
        ),
        migrations.CreateModel(
            name='AreaCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='qff.area')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area_cell', to='qff.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West'), ('nw', 'Northwest'), ('ne', 'Northeast'), ('sw', 'Southwest'), ('se', 'Southeast'), ('up', 'Up'), ('down', 'Down'), ('in', 'In'), ('out', 'Out')], max_length=8)),
                ('is_hidden', models.BooleanField(default=False)),
                ('lock_kind', models.CharField(choices=[('none', 'None'), ('key', 'Key'), ('device', 'Device'), ('quest', 'Quest')], default='none', max_length=16)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits_out', to='qff.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits_in', to='qff.room')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterExitSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits_seen', to='qff.character')),
                ('room_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='qff.roomexit')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_visits', to='qff.character')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_visits', to='qff.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'room'), name='qff_charroomvisit_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['current_room', 'last_activity_at'], name='qff_charact_current_225aca_idx'),
        ),
        migrations.AddIndex(
            model_name='areacell',
            index=models.Index(fields=['area', 'x', 'y'], name='qff_areacel_area_id_fa0b61_idx'),
        ),
        migrations.AddConstraint(
            model_name='areacell',
            constraint=models.UniqueConstraint(fields=('area', 'x', 'y'), name='qff_areacell_area_xy_uniq'),
        ),
        migrations.AddConstraint(
            model_name='roomexit',
            constraint=models.UniqueConstraint(fields=('from_room', 'direction'), name='qff_roomexit_from_direction_uniq'),
        ),
        migrations.AddConstraint(
            model_name='characterexitseen',
            constraint=models.UniqueConstraint(fields=('character', 'room_exit'), name='qff_charexitseen_uniq'),
        ),
    ]
