# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


def copy_current_room_to_spawn(apps, schema_editor):
    Character = apps.get_model("qff", "Character")
    for c in Character.objects.all().only("id", "current_room_id", "spawn_room_id"):
        if c.spawn_room_id is None:
            c.spawn_room_id = c.current_room_id
            c.save(update_fields=["spawn_room_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("qff", "0003_area_theme_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="spawn_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="respawn_characters",
                to="qff.room",
            ),
        ),
        migrations.RunPython(copy_current_room_to_spawn, noop_reverse),
        migrations.AlterField(
            model_name="character",
            name="spawn_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="respawn_characters",
                to="qff.room",
            ),
        ),
    ]
