# Generated by Django 6.0.3 on 2026-04-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0005_remove_qff_seed_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(blank=True, max_length=64)),
                ('slot', models.CharField(choices=[('head', 'Head'), ('main_hand', 'Main Hand'), ('off_hand', 'Off-Hand'), ('chest', 'Chest'), ('feet', 'Feet'), ('ring', 'Ring'), ('amulet', 'Amulet')], max_length=16)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('lore', models.TextField(blank=True)),
                ('lore_chance', models.PositiveSmallIntegerField(blank=True, help_text='1–100; null = lore available without unlock roll on instance.', null=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('legendary', 'Legendary'), ('unique', 'Unique')], default='common', max_length=16)),
                ('damage', models.PositiveSmallIntegerField(default=0)),
                ('dmg_type', models.CharField(choices=[('physical', 'Physical'), ('magic', 'Magic')], default='physical', max_length=16)),
                ('element', models.CharField(blank=True, max_length=32)),
                ('hidden_special_effect', models.CharField(choices=[('none', 'None'), ('crit_chain', 'Crit chain'), ('lifesteal', 'Lifesteal'), ('mana_on_hit', 'Mana on hit')], default='none', max_length=32)),
                ('two_handed', models.BooleanField(default=False)),
                ('req_gains', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('req_moves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('req_guts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('req_smarts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('req_sense', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('req_rizz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bonus_gains', models.SmallIntegerField(default=0)),
                ('bonus_moves', models.SmallIntegerField(default=0)),
                ('bonus_guts', models.SmallIntegerField(default=0)),
                ('bonus_smarts', models.SmallIntegerField(default=0)),
                ('bonus_sense', models.SmallIntegerField(default=0)),
                ('bonus_rizz', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='cur_health',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='character',
            name='cur_mana',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='gains',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='guts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='character',
            name='last_room_broadcast_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='character',
            name='max_mana',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='moves',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='rizz',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='sense',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='smarts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='search_chance',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('chars_failed_to_inspect', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='qff.item')),
                ('owner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_item_instances', to='qff.character')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_items', to='qff.room')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='amulet_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='chest_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='feet_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='head_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='main_hand_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='off_hand_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.iteminstance'),
        ),
        migrations.CreateModel(
            name='RoomBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='qff.room')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_broadcasts_sent', to='qff.character')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='iteminstance',
            index=models.Index(fields=['owner_character', 'room'], name='qff_itemins_owner_c_9b389b_idx'),
        ),
        migrations.AddIndex(
            model_name='roombroadcast',
            index=models.Index(fields=['room', 'id'], name='qff_roombro_room_id_e3f7c4_idx'),
        ),
    ]
