# Generated by Django 6.0.3 on 2026-04-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0007_seed_starting_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombroadcast',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
