# Generated by Django 6.0.3 on 2026-04-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0009_inventory_newest_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='armor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='hidden_bonus_stat',
            field=models.CharField(blank=True, choices=[('', 'None'), ('gains', 'Gains'), ('moves', 'Moves'), ('guts', 'Guts'), ('smarts', 'Smarts'), ('sense', 'Sense'), ('rizz', 'Rizz')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='item',
            name='hidden_bonus_value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
