# Generated by Django 6.0.3 on 2026-04-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0010_item_armor_hidden_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='neglect_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Unowned floor items: times a player left the room; at 4 the instance is removed.'),
        ),
    ]
