# Generated by Django 6.0.3 on 2026-04-05 02:44

from django.db import migrations, models
from django.db.models import F


def backfill_floor_dropped_at(apps, schema_editor):
    ItemInstance = apps.get_model("qff", "ItemInstance")
    ItemInstance.objects.filter(
        room_id__isnull=False,
        owner_character_id__isnull=True,
        floor_dropped_at__isnull=True,
    ).update(floor_dropped_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0011_iteminstance_neglect_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='floor_dropped_at',
            field=models.DateTimeField(blank=True, help_text='When this instance was last placed on the floor (drop); null if owned/in inventory.', null=True),
        ),
        migrations.RunPython(backfill_floor_dropped_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='iteminstance',
            name='neglect_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Unowned floor items: times a player left the room; at 4 the instance may be removed.'),
        ),
    ]
