# Generated by Django 6.0.3 on 2026-04-05 02:55

import django.db.models.deletion
from django.db import migrations, models


def link_default_starter_items(apps, schema_editor):
    Item = apps.get_model("qff", "Item")
    CharacterClass = apps.get_model("qff", "CharacterClass")
    mapping = (
        ("starter_head_item_id", "baseball-cap", "head"),
        ("starter_chest_item_id", "denim-jacket", "chest"),
        ("starter_main_hand_item_id", "wooden-stick", "main_hand"),
    )
    updates = {}
    for field, slug, _slot in mapping:
        it = Item.objects.filter(slug=slug).first()
        if it:
            updates[field] = it.id
    if len(updates) == 3:
        CharacterClass.objects.all().update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0012_iteminstance_floor_dropped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='priority_stat_1',
            field=models.CharField(choices=[('gains', 'Gains'), ('moves', 'Moves'), ('guts', 'Guts'), ('smarts', 'Smarts'), ('sense', 'Sense'), ('rizz', 'Rizz')], default='gains', max_length=16),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='priority_stat_2',
            field=models.CharField(choices=[('gains', 'Gains'), ('moves', 'Moves'), ('guts', 'Guts'), ('smarts', 'Smarts'), ('sense', 'Sense'), ('rizz', 'Rizz')], default='guts', max_length=16),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starter_chest_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.item'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starter_head_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.item'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='starter_main_hand_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.item'),
        ),
        migrations.RunPython(link_default_starter_items, migrations.RunPython.noop),
    ]
