# Generated by Django 6.0.3 on 2026-04-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0013_character_class_expand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='starter_head_item',
        ),
    ]
