# Generated by Django 6.0.3 on 2026-04-05 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0015_backfill_characterclass_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='roomexit',
            name='key_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_keys_for', to='qff.item'),
        ),
        migrations.AddField(
            model_name='roomexit',
            name='key_unlock_scope',
            field=models.CharField(choices=[('realm_timed', 'Realm (timed)'), ('character', 'Character only')], default='realm_timed', max_length=16),
        ),
        migrations.AddField(
            model_name='roomexit',
            name='unlock_duration_seconds',
            field=models.PositiveIntegerField(default=600, help_text='Realm-timed unlock duration (KEY realm_timed, DEVICE).'),
        ),
        migrations.CreateModel(
            name='Interactable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('sign', 'Sign'), ('chest', 'Chest'), ('button', 'Button'), ('lever', 'Lever'), ('other', 'Other')], default='other', max_length=16)),
                ('inspect_text', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactables', to='qff.room')),
                ('unlocks_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactable_unlocks', to='qff.roomexit')),
            ],
            options={
                'ordering': ['room_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='roomexit',
            name='device_interactable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_for_exits', to='qff.interactable'),
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='qff.room')),
            ],
            options={
                'ordering': ['room_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='qff.quest')),
            ],
            options={
                'ordering': ['quest_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NpcDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='qff.npc')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc_dialogues', to='qff.quest')),
                ('quest_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc_dialogues', to='qff.queststate')),
            ],
            options={
                'ordering': ['npc_id', '-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='qff.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_progress', to='qff.quest')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters_here', to='qff.queststate')),
            ],
        ),
        migrations.AddField(
            model_name='roomexit',
            name='quest_required_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits_requiring_state', to='qff.queststate'),
        ),
        migrations.CreateModel(
            name='QuestTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='qff.queststate')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='qff.quest')),
                ('requires_item', models.ForeignKey(blank=True, help_text='If set, character must carry this item template (inventory or equipped).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.item')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='qff.queststate')),
            ],
            options={
                'ordering': ['quest_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grant_xp', 'Grant XP'), ('grant_gold', 'Grant gold'), ('grant_item', 'Grant item (new instance)'), ('remove_item_template', 'Remove item by template'), ('realm_unlock_exit_timed', 'Realm unlock exit (timed)'), ('character_unlock_exit', 'Character unlock exit')], max_length=32)),
                ('amount', models.IntegerField(default=0, help_text='XP, gold, or unlock duration in minutes for timed realm unlock.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='qff.item')),
                ('room_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_effects', to='qff.roomexit')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='qff.questtransition')),
            ],
            options={
                'ordering': ['transition_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interactable',
            name='quest_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactables', to='qff.questtransition'),
        ),
        migrations.CreateModel(
            name='RealmExitUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('room_exit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realm_unlock', to='qff.roomexit')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterExitUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = permanent for this character.', null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_unlocks', to='qff.character')),
                ('room_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_unlocks', to='qff.roomexit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character', 'room_exit'), name='qff_charexitunlock_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='npc',
            constraint=models.UniqueConstraint(fields=('room', 'slug'), name='qff_npc_room_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='queststate',
            constraint=models.UniqueConstraint(fields=('quest', 'slug'), name='qff_queststate_quest_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='characterquestprogress',
            constraint=models.UniqueConstraint(fields=('character', 'quest'), name='qff_charquestprogress_uniq'),
        ),
        migrations.AddConstraint(
            model_name='interactable',
            constraint=models.UniqueConstraint(fields=('room', 'slug'), name='qff_interactable_room_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='realmexitunlock',
            index=models.Index(fields=['expires_at'], name='qff_realmex_expires_68dc7f_idx'),
        ),
    ]
