# Generated by Django 6.0.3 on 2026-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0016_quests_npcs_interactables_unlocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
