# Generated by Django 6.0.3 on 2026-04-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0032_monster_combat_extras'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iteminstance',
            new_name='qff_itemins_contain_d07eeb_idx',
            old_name='qff_iteminst_container_room_idx',
        ),
        migrations.RenameIndex(
            model_name='monsterinstance',
            new_name='qff_monster_current_3bf8d6_idx',
            old_name='qff_monster_current_0f3f91_idx',
        ),
        migrations.RenameIndex(
            model_name='monsterinstance',
            new_name='qff_monster_next_ac_77fc34_idx',
            old_name='qff_monster_next_ac_8b4f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='monsterinstance',
            new_name='qff_monster_next_pu_47cc42_idx',
            old_name='qff_monster_next_pu_7a1d8e_idx',
        ),
        migrations.AddField(
            model_name='monstertemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monstertemplate',
            name='hidden_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='container_interactable',
            field=models.ForeignKey(blank=True, help_text='If set, this floor item is inside this container (not loose in the room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_items', to='qff.interactable'),
        ),
        migrations.AlterField(
            model_name='monstertemplate',
            name='crit_chance_bonus_pct',
            field=models.SmallIntegerField(default=0, help_text='Percentage points added to crit chance (same semantics as Item).'),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='interactable',
            field=models.ForeignKey(blank=True, help_text='If set, this pickup appears only while this container is focused (opened).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_room_items', to='qff.interactable'),
        ),
    ]
