# Generated by Django 6.0.3 on 2026-04-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0035_reflavor_glyphs_and_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterinstance',
            name='monster_strike_pending',
            field=models.BooleanField(default=False, help_text='Legacy field; kept for migrations. Combat no longer uses a separate wind-up tick.'),
        ),
    ]
