# Generated by Cursor for monster lore DC, attack weapon label, remove hidden_description_chance.

from django.db import migrations, models


def forwards_copy_hidden_chance_to_lore_dc(apps, schema_editor):
    MonsterTemplate = apps.get_model("qff", "MonsterTemplate")
    for t in MonsterTemplate.objects.all():
        if getattr(t, "hidden_description_chance", None) is not None:
            t.lore_dc = t.hidden_description_chance
            t.save(update_fields=["lore_dc"])


class Migration(migrations.Migration):
    dependencies = [
        ("qff", "0042_readable_container_search_rewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="monstertemplate",
            name="lore_dc",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text="Look/inspect: hero needs d100+Smarts (encumbered) ≥ this DC for hidden text; null uses template level.",
            ),
        ),
        migrations.AddField(
            model_name="monstertemplate",
            name="attack_weapon_label",
            field=models.CharField(
                blank=True,
                max_length=120,
                help_text="Optional flavor for monster hit lines (e.g. claws, rusty blade).",
            ),
        ),
        migrations.RunPython(forwards_copy_hidden_chance_to_lore_dc, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="monstertemplate",
            name="hidden_description_chance",
        ),
    ]
