# Generated by Django on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0047_room_search_floor_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstertemplate',
            name='quest_drops',
            field=models.JSONField(blank=True, default=list, help_text='Quest-only drop rows (separate from loot_table). Each row may include quest_state_id, item_slug/item_id, per_kill_qty, chance.'),
        ),
        migrations.AddField(
            model_name='questtransition',
            name='requires_item_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity required across inventory stacks + equipped.'),
        ),
    ]
