# Generated by Django 6.0.3 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qff",
            "0048_rename_qff_roomitemclaim_room_ch_idx_qff_roomite_room_it_35e066_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="characterroomsearchclaim",
            name="successful_search",
            field=models.BooleanField(
                default=False,
                help_text="Set after this hero's first successful search roll in this room.",
            ),
        ),
    ]

