# Generated by Cursor for per-character item template lore unlocks

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qff", "0049_characterroomsearchclaim_successful_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterItemLoreUnlocked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_lore_unlocks",
                        to="qff.character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lore_unlocked_for_characters",
                        to="qff.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "item"),
                        name="qff_charitemlore_uniq",
                    )
                ],
            },
        ),
    ]
