# Generated by Django; monster attack verb (optional combat flavor)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qff", "0050_characteritemloreunlocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="monstertemplate",
            name="attack_verb",
            field=models.CharField(
                blank=True,
                help_text="Optional verb for strikes/misses (e.g. bites, claws, slashes). Empty = default text.",
                max_length=80,
            ),
        ),
    ]
