# Generated by Django 6.0.3 on 2026-05-05 14:13
#
# Hand-pruned: ``makemigrations`` also picked up auto-generated ``RenameIndex``
# and ``AlterField`` operations for unrelated model drift (Item/Interactable
# help_text, Roomtime* index name churn). Those renames target indexes that
# don't exist on every deployment ("no such index: qff_roomitemclaim_room_ch_idx"
# on sqlite during ``migrate``), so we keep only the index additions this
# migration is actually about: speeding up the lazy-sim aggregate-MIN watermark
# in ``qff.monster_sim.run_lazy_simulation``.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0052_roombroadcast_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['next_action_at'], name='qff_charact_next_ac_c6eaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['pending_leave_at'], name='qff_charact_pending_a7d99f_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['died_at'], name='qff_charact_died_at_ac43c0_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['lair_next_spawn_at'], name='qff_room_lair_ne_ec6c31_idx'),
        ),
    ]
