# Generated by Django 6.0.3 on 2026-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qff', '0053_lazy_sim_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactable',
            name='read_text',
            field=models.TextField(blank=True, help_text='Long text for read; falls back to inspect_text when empty.'),
        ),
        migrations.AlterField(
            model_name='interactable',
            name='untranslated',
            field=models.BooleanField(default=False, help_text='If true, /read uses read_text only; heroes without the 👽 glyph get a denial line and never see the alien text. look/inspect still use inspect_text.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='consumable',
            field=models.BooleanField(default=False, help_text='If true, eat/drink/use/read can consume from inventory (non-consumables cannot).'),
        ),
    ]
