# Generated by Django 6.0.3 on 2026-03-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='labels',
            field=models.ManyToManyField(related_name='quotes', through='quotes.QuoteLabelAssignment', to='quotes.quotelabel'),
        ),
    ]
