# Generated by Django — data migrate public -> published, then alter choices.

from django.db import migrations, models


def forwards_visibility(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    Quote.objects.filter(visibility="public").update(visibility="published")


def backwards_visibility(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    Quote.objects.filter(visibility="published").update(visibility="public")


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_quote_labels_through"),
    ]

    operations = [
        migrations.RunPython(forwards_visibility, backwards_visibility),
        migrations.AlterField(
            model_name="quote",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("published", "Published")],
                default="private",
                max_length=20,
            ),
        ),
    ]
