# Generated by Django 6.0.3 on 2026-04-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendcomment',
            new_name='friend_comm_content_7ec520_idx',
            old_name='friend_comm_content_8a1c9e_idx',
        ),
    ]
