/** Frontend map: one place for achievement medal emojis (aligned with backend slugs in `achievements.services`). */
const SLUG_TO_EMOJI: Record<string, string> = {
  archivist: "📚",
  town_crier: "📣",
  whatif_wiz: "🧙",
  whatif_warrior: "⚔️",
  whatif_dece_proposer: "🤔",
  pondclicker_tier_1_pond: "🐌",
  pondclicker_tier_2_pond: "🦐",
  pondclicker_tier_3_pond: "🐟",
  pondclicker_tier_4_pond: "🐸",
  pondclicker_tier_5_pond: "🦆",
  pondclicker_tier_6_pond: "🦦",
  pondclicker_tier_7_pond: "🪷",
  pondclicker_pond_pawn: "🪷",
  pondclicker_tadpole_traveler: "🪷",
  pondclicker_pond_pioneer: "🪷",
  pondclicker_lily_pad_leaper: "🪷",
  pondclicker_wetland_wanderer: "🪷",
  pondclicker_marsh_warden: "🪷",
  pondclicker_current_commander: "🪷",
  pondclicker_stillwater_strategist: "🪷",
  pondclicker_ecosystem_architect: "🪷",
  pondclicker_pond_potentate: "🪷",
  sharing_is_caring: "🤝",
  something_borrowed: "👜",
  good_as_new: "✨",
  familial_arborist: "🌳",
  thats_amore: "🍝",
  tasty_plans: "👨‍🍳",
  smorgasbord: "\u{1F37D}",
  i_can_smell_it_from_here: "\u{1F963}",
  month_of_music: "\u{1F3B6}",
  music_lover: "\u{1F493}",
  musically_multiloquent: "\u{1F4AC}",
  schedule_coordinator: "🗓️",
  estates_farmhand: "🌾",
  estates_highwayman: "👣",
  estates_lookout: "🗼",
  estates_gatekeeper: "⛩️",
  estates_monarch: "👑",
  estates_royal: "🏰",
  estates_noble: "🛡️",
  estates_peasant: "⚒️",
};

const DEFAULT_EMOJI = "🏆";

export function emojiForAchievementSlug(slug: string): string {
  return SLUG_TO_EMOJI[slug] ?? DEFAULT_EMOJI;
}
