/**
 * Dev report + generator for PondClicker 2 evolution prices.
 * Run: npm run clicker2:pricing-report
 * Write generated map: npm run clicker2:pricing-generate
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  EVOLUTION_PAYBACK_SEC,
  evolutionChainKind,
  formatPaybackDuration,
  generateSpecialtyPrices,
  marginalValueAtUnlock,
  paybackSec,
  validatePricingTable,
} from "../src/clicker2/evolutionPricing";
import {
  specialtiesForDenizen,
  specialtyTierIndex,
  SPECIALTIES,
  type SpecialtyDef,
} from "../src/clicker2/specialties";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GENERATED_PATH = join(
  __dirname,
  "../src/clicker2/evolutionPrices.generated.ts",
);

const WRITE = process.argv.includes("--write");

function report(): void {
  const prices = generateSpecialtyPrices(SPECIALTIES);
  const violations = validatePricingTable(SPECIALTIES, prices);

  const header = [
    "id",
    "chain",
    "tier",
    "unlock",
    "current_price",
    "marginal_eps",
    "marginal_click",
    "income_per_sec",
    "payback_current",
    "proposed_price",
    "payback_proposed",
  ].join("\t");

  console.log(header);

  for (const s of SPECIALTIES) {
    const tier = specialtyTierIndex(s);
    const { marginalEps, marginalClick, incomePerSec } =
      marginalValueAtUnlock(s);
    const proposed = prices[s.id]!;
    const unlock =
      s.unlockAllTimeEnergy != null
        ? `${s.unlockAllTimeEnergy} all-time`
        : `${s.unlockOwned} owned`;
    console.log(
      [
        s.id,
        s.denizenId,
        tier,
        unlock,
        s.price,
        marginalEps.toFixed(4),
        marginalClick.toFixed(4),
        incomePerSec.toFixed(4),
        formatPaybackDuration(paybackSec(s.price, incomePerSec)),
        proposed,
        formatPaybackDuration(paybackSec(proposed, incomePerSec)),
      ].join("\t"),
    );
  }

  console.error(`\nTarget payback: ${EVOLUTION_PAYBACK_SEC}s`);
  console.error(`Violations: ${violations.length}`);
  for (const v of violations.slice(0, 30)) {
    console.error(`  [${v.kind}] #${v.specialtyId}: ${v.message}`);
  }
  if (violations.length > 30) {
    console.error(`  ... and ${violations.length - 30} more`);
  }

  if (WRITE) {
    writeGeneratedFile(prices);
    console.error(`\nWrote ${GENERATED_PATH}`);
  }

  if (violations.length > 0 && !WRITE) {
    process.exitCode = 1;
  }
}

function writeGeneratedFile(prices: Record<number, number>): void {
  const lines = Object.entries(prices)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([id, price]) => `  ${id}: ${price},`);

  const content = `/** AUTO-GENERATED by scripts/clicker2-evolution-pricing-report.ts --write */
/** Target payback ~${EVOLUTION_PAYBACK_SEC}s at reference unlock. Do not edit by hand. */

export const SPECIALTY_PRICE_BY_ID: Readonly<Record<number, number>> = {
${lines.join("\n")}
};

export function specialtyCatalogPrice(id: number, fallback = 1): number {
  return SPECIALTY_PRICE_BY_ID[id] ?? fallback;
}
`;

  writeFileSync(GENERATED_PATH, content, "utf8");
}

report();
