/**
 * Generate pairing evolution catalog + prices.
 * Price per pair (L, H): 50% of L’s 2nd evolution + 50% of H’s 1st evolution.
 * Run: npm run clicker2:pairing-generate
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  generatePairingSpecialtyDefs,
  PAIRING_SPECIALTY_ID_START,
  pairingSpecialtyCount,
} from "../src/clicker2/pairingEvolutions";
import { SPECIALTY_PRICE_BY_ID } from "../src/clicker2/evolutionPrices.generated";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PRICES_PATH = join(__dirname, "../src/clicker2/evolutionPrices.generated.ts");
const PAIRING_PATH = join(
  __dirname,
  "../src/clicker2/pairingSpecialties.generated.ts",
);

function catalogPrice(id: number): number {
  return SPECIALTY_PRICE_BY_ID[id] ?? 1;
}

function serializeSpecialty(def: ReturnType<typeof generatePairingSpecialtyDefs>[0]): string {
  const pairingUnlock = JSON.stringify(def.pairingUnlock);
  const effects = JSON.stringify(def.effects, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : `    ${line}`))
    .join("\n");
  return `  {
    id: ${def.id},
    name: ${JSON.stringify(def.name)},
    denizenId: ${JSON.stringify(def.denizenId)},
    unlockOwned: 0,
    pairingUnlock: ${pairingUnlock},
    pairingLowerDenizenId: ${JSON.stringify(def.pairingLowerDenizenId)},
    pairingHigherDenizenId: ${JSON.stringify(def.pairingHigherDenizenId)},
    price: specialtyCatalogPrice(${def.id}),
    effect: ${JSON.stringify(def.effect)},
    effects: ${effects},
    effectText: ${JSON.stringify(def.effectText)},
    ecologyNote: ${JSON.stringify(def.ecologyNote)},
  }`;
}

function writePairingSpecialtiesFile(
  defs: ReturnType<typeof generatePairingSpecialtyDefs>,
): void {
  const body = defs.map(serializeSpecialty).join(",\n");
  const content = `/** AUTO-GENERATED by scripts/clicker2-pairing-generate.ts — do not edit by hand. */

import { specialtyCatalogPrice } from "./evolutionPrices.generated";
import type { SpecialtyDef } from "./specialties";

export const PAIRING_SPECIALTIES: readonly SpecialtyDef[] = [
${body},
];
`;
  writeFileSync(PAIRING_PATH, content, "utf8");
}

function mergePrices(
  defs: ReturnType<typeof generatePairingSpecialtyDefs>,
): void {
  const merged: Record<number, number> = { ...SPECIALTY_PRICE_BY_ID };
  for (const def of defs) {
    merged[def.id] = def.price;
  }
  const lines = Object.entries(merged)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([id, price]) => `  ${id}: ${price},`);

  const content = `/** AUTO-GENERATED by scripts/clicker2-evolution-pricing-report.ts --write */
/** Pairing ids ${PAIRING_SPECIALTY_ID_START}+ merged by scripts/clicker2-pairing-generate.ts */
/** Target payback ~120s at reference unlock. Do not edit pairing prices by hand. */

export const SPECIALTY_PRICE_BY_ID: Readonly<Record<number, number>> = {
${lines.join("\n")}
};

export function specialtyCatalogPrice(id: number, fallback = 1): number {
  return SPECIALTY_PRICE_BY_ID[id] ?? fallback;
}
`;
  writeFileSync(PRICES_PATH, content, "utf8");
}

function main(): void {
  const expected = pairingSpecialtyCount();
  const defs = generatePairingSpecialtyDefs(catalogPrice);
  if (defs.length !== expected) {
    throw new Error(`Expected ${expected} pairings, got ${defs.length}`);
  }
  const ids = new Set(defs.map((d) => d.id));
  if (ids.size !== defs.length) {
    throw new Error("Duplicate pairing specialty ids");
  }
  const lastId = defs[defs.length - 1]!.id;
  console.error(`Generated ${defs.length} pairings (ids ${PAIRING_SPECIALTY_ID_START}–${lastId})`);
  mergePrices(defs);
  writePairingSpecialtiesFile(defs);
  console.error(`Wrote ${PAIRING_PATH}`);
  console.error(`Updated ${PRICES_PATH}`);
}

main();
