# Generated by Django 6.0.3 on 2026-04-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ical', 'iCal URL'), ('manual', 'Manual'), ('google_oauth', 'Google OAuth (future)')], default='ical', max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('ical_url', models.URLField(blank=True, default='', max_length=2048)),
                ('color', models.CharField(choices=[('lilypad', 'Lilypad'), ('sky', 'Sky'), ('nautical', 'Nautical'), ('gray', 'Gray')], default='lilypad', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_etag', models.CharField(blank=True, default='', max_length=255)),
                ('last_modified_header', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uid', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('source_timezone', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendarsource')),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarsource',
            index=models.Index(fields=['owner'], name='calendars_c_owner_i_59dac7_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsource',
            index=models.Index(fields=['is_active', 'last_synced_at'], name='calendars_c_is_acti_189c20_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarsource',
            constraint=models.UniqueConstraint(condition=models.Q(('ical_url', ''), _negated=True), fields=('owner', 'ical_url'), name='uniq_calendar_source_owner_ical_url'),
        ),
        migrations.AddConstraint(
            model_name='calendarsource',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'manual')), fields=('owner', 'source_type'), name='uniq_calendar_source_manual_per_owner'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'start_at'], name='calendars_e_owner_i_fd796e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source', 'start_at'], name='calendars_e_source__1d00f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('external_uid', ''), _negated=True), fields=('source', 'external_uid'), name='uniq_event_source_external_uid'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='event_end_at_after_start_at'),
        ),
    ]
