# Generated by Django 6.0.3 on 2026-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendar_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsubscription',
            name='include_all_visible',
            field=models.BooleanField(default=False, help_text='When true, feed includes everyone visible to the owner (resolved on each poll).'),
        ),
    ]
