# Generated manually for HarborShipUpgradeDef + HarborStageUnlock + seeds.

from django.db import migrations, models


def seed_ship_upgrades_and_stages(apps, schema_editor):
    HarborShipUpgradeDef = apps.get_model("harbor", "HarborShipUpgradeDef")
    HarborStageUnlock = apps.get_model("harbor", "HarborStageUnlock")

    for row in [
        {
            "slug": "fishing-nets",
            "name": "Fishing Nets",
            "description": "Adds +5 fish to each voyage yield.",
            "stage_min": 1,
            "stage_max": None,
            "tags": ["age1", "ship_upgrade"],
            "extra": {"yield_bonus": {"food": 5}, "cost": {"food": 15, "wealth": 15}},
            "enabled": True,
            "sort_order": 1,
        },
        {
            "slug": "lumber-loft",
            "name": "Lumber Loft",
            "description": "Adds +5 timber to each voyage yield.",
            "stage_min": 1,
            "stage_max": None,
            "tags": ["age1", "ship_upgrade"],
            "extra": {"yield_bonus": {"timber": 5}, "cost": {"timber": 15, "wealth": 15}},
            "enabled": True,
            "sort_order": 2,
        },
        {
            "slug": "ships-manifest",
            "name": "Ship's Manifest",
            "description": "Adds +5 wealth to each voyage yield.",
            "stage_min": 1,
            "stage_max": None,
            "tags": ["age1", "ship_upgrade"],
            "extra": {"yield_bonus": {"wealth": 5}, "cost": {"wealth": 30}},
            "enabled": True,
            "sort_order": 3,
        },
    ]:
        HarborShipUpgradeDef.objects.create(**row)

    stages = [
        (
            1,
            "Dock",
            "Hand-built harbor",
            "",
            "",
            "Limited attention is the real resource.",
            ["food", "timber", "wealth"],
            ["population"],
            ["trade"],
            ["harbor", "buildings"],
            ["starter"],
            False,
            1,
        ),
        (
            2,
            "Cove",
            "Settled cove",
            "What gets built first?",
            "Buildings vs. ships vs. arrivals.",
            "Choose what to skip.",
            ["stone"],
            ["population", "morale", "prestige"],
            [],
            ["arrivals", "buildings"],
            [],
            False,
            4,
        ),
        (
            3,
            "Wharf",
            "Working wharf",
            "Who keeps the harbor safe?",
            "Patrol vs. profit.",
            "Pressure builds invisibly until it breaks.",
            ["metal"],
            ["security"],
            ["patrol"],
            [],
            [],
            False,
            4,
        ),
        (
            4,
            "Quay",
            "Diplomatic quay",
            "Who do you befriend?",
            "Allies and obligations.",
            "Influence is its own currency.",
            [],
            ["influence"],
            ["diplomacy"],
            [],
            [],
            False,
            5,
        ),
        (
            5,
            "Pier",
            "Industrial pier",
            "What can you make in bulk?",
            "Specialization vs. resilience.",
            "Industry compounds.",
            [],
            [],
            ["industry"],
            [],
            [],
            False,
            5,
        ),
        (
            6,
            "Marina",
            "Civic marina",
            "Who do you save?",
            "Relief work vs. self-reliance.",
            "Values are revealed by triage.",
            [],
            ["readiness"],
            ["relief"],
            [],
            [],
            False,
            6,
        ),
        (
            7,
            "Anchorage",
            "Crowded anchorage",
            "Who gets the berth?",
            "Sanitation under crowding.",
            "Maintenance is identity.",
            [],
            ["sanitation"],
            [],
            [],
            [],
            False,
            6,
        ),
        (
            8,
            "Port",
            "Regional port",
            "How do you say no?",
            "Throughput vs. character.",
            "Refusal shapes the harbor.",
            [],
            ["congestion"],
            [],
            [],
            [],
            False,
            7,
        ),
        (
            9,
            "Harbor",
            "Major harbor",
            "What is your harbor *for*?",
            "Specialization peaks.",
            "Clarity of purpose beats raw scale.",
            [],
            [],
            [],
            [],
            [],
            False,
            7,
        ),
        (
            10,
            "Bay",
            "Far horizons",
            "What can you reach?",
            "Long-range voyages, long delays.",
            "Time horizons stretch.",
            ["oil"],
            [],
            [],
            [],
            [],
            False,
            8,
        ),
        (
            11,
            "Capital",
            "Capital harbor",
            "What do others copy?",
            "Influence at scale.",
            "You are watched.",
            ["rareMinerals"],
            [],
            [],
            [],
            [],
            False,
            8,
        ),
        (
            12,
            "Endgame",
            "Doctrine of the harbor",
            "What is this harbor *known for*?",
            "Permanent identity.",
            "Choose, then live with it.",
            [],
            [],
            [],
            ["doctrine", "policies"],
            ["endgame"],
            True,
            9,
        ),
    ]
    for (
        sid,
        title,
        era,
        aq,
        ct,
        ml,
        resources,
        metrics,
        voyage_types,
        panels,
        content_tags,
        doctrine_unlocked,
        base_cmd,
    ) in stages:
        HarborStageUnlock.objects.create(
            stage_id=sid,
            title=title,
            era=era,
            age_question=aq,
            core_tension=ct,
            main_lesson=ml,
            resources=resources,
            metrics=metrics,
            voyage_types=voyage_types,
            panels=panels,
            content_tags=content_tags,
            doctrine_unlocked=doctrine_unlocked,
            base_command_per_day=base_cmd,
        )


def unseed(apps, schema_editor):
    HarborShipUpgradeDef = apps.get_model("harbor", "HarborShipUpgradeDef")
    HarborStageUnlock = apps.get_model("harbor", "HarborStageUnlock")
    HarborShipUpgradeDef.objects.all().delete()
    HarborStageUnlock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("harbor", "0005_timber_skiff_two_day_voyage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarborShipUpgradeDef",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("stage_min", models.PositiveSmallIntegerField(default=1)),
                ("stage_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="HarborStageUnlock",
            fields=[
                ("stage_id", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("era", models.CharField(max_length=120)),
                ("age_question", models.TextField(blank=True)),
                ("core_tension", models.TextField(blank=True)),
                ("main_lesson", models.TextField(blank=True)),
                ("resources", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=list)),
                ("voyage_types", models.JSONField(blank=True, default=list)),
                ("panels", models.JSONField(blank=True, default=list)),
                ("content_tags", models.JSONField(blank=True, default=list)),
                ("doctrine_unlocked", models.BooleanField(default=False)),
                ("base_command_per_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stage_id"],
            },
        ),
        migrations.RunPython(seed_ship_upgrades_and_stages, unseed),
    ]
