# Generated by Django 6.0.3 on 2026-06-03 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('played_at', models.DateField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorenado_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='gray.200', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('team', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scorenado.game')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreboardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scored_by_rounds', models.BooleanField(default=False)),
                ('low_score_wins', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorenado_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='scorenado.scoreboardtemplate'),
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_scored', models.BooleanField(default=True)),
                ('is_manual_total', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='scorenado.scoreboardtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scorenado.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scorenado.gameplayer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scorenado.templatecategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='gameplayer',
            index=models.Index(fields=['game', 'sort_order'], name='scorenado_g_game_id_0eab45_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreboardtemplate',
            index=models.Index(fields=['owner_user', '-updated_at'], name='scorenado_s_owner_u_6a379a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['owner_user', '-updated_at'], name='scorenado_g_owner_u_8184fe_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['owner_user', 'is_finalized'], name='scorenado_g_owner_u_97a613_idx'),
        ),
        migrations.AddIndex(
            model_name='templatecategory',
            index=models.Index(fields=['template', 'sort_order'], name='scorenado_t_templat_67aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', 'category'], name='scorenado_s_game_id_de132e_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('game', 'category', 'player'), name='uniq_scorenado_score_game_category_player'),
        ),
    ]
