# Generated by Django 6.0.3 on 2026-04-01 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIfQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('answer_4', models.CharField(max_length=255)),
                ('answer_5', models.CharField(max_length=255)),
                ('answer_6', models.CharField(max_length=255)),
                ('sessions_used_count', models.PositiveIntegerField(default=0)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('total_scores', models.PositiveIntegerField(default=0)),
                ('total_skips', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatIfSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('status', models.CharField(choices=[('pre_lobby', 'Pre Lobby'), ('open', 'Open'), ('turn', 'Turn'), ('voting', 'Voting'), ('reveal', 'Reveal'), ('post_results', 'Post Results'), ('ended', 'Ended')], default='open', max_length=30)),
                ('challenge_mode', models.BooleanField(default=False)),
                ('state_version', models.PositiveIntegerField(default=1)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatIfPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('avatar_emoji', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('skips_remaining', models.PositiveIntegerField(default=1)),
                ('player_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatif_players', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='whatif.whatifsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhatIfGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatif_wins', to=settings.AUTH_USER_MODEL)),
                ('winner_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='whatif.whatifplayer')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='whatif.whatifsession')),
            ],
        ),
        migrations.CreateModel(
            name='WhatIfQuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_usages', to='whatif.whatifquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_usages', to='whatif.whatifsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question', 'session'), name='uniq_whatif_question_session')],
            },
        ),
    ]
