# Generated by Django 6.0.3 on 2026-04-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_item_custody_pending_acceptance_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_holder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closet_held_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closet_owned_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
