# Generated by Django 6.0.3 on 2026-04-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_protect_item_user_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_holder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_held_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_owned_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
