# Generated by Django 6.0.3 on 2026-05-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0006_user_soft_delete_and_closet_row_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to='closet.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_hidden_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'item'], name='closet_item_user_id_eae43c_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
