# Generated by Django 6.0.3 on 2026-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth0_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
