# Generated by Django 6.0.3 on 2026-04-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_meal_slot_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meal_pantry_enabled',
            field=models.BooleanField(default=False, help_text='When true, show pantry inventory and related grocery hints.'),
        ),
    ]
