# Generated by Django 6.0.3 on 2026-04-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealpartnerdisconnectrequest',
            new_name='meal_mealpa_recipie_a72f45_idx',
            old_name='meal_mealpar_recipie_6d0_idx',
        ),
        migrations.RenameIndex(
            model_name='mealpartnerdisconnectrequest',
            new_name='meal_mealpa_initiat_c4c764_idx',
            old_name='meal_mealpar_initiat_55d_idx',
        ),
    ]
