# Generated by Django 6.0.3 on 2026-04-11 20:01

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_meal_image_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_published_to_friends',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='MealCategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('meal_type', 'Meal type'), ('cuisine', 'Cuisine'), ('time', 'Time')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_category_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['axis', 'name'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='cuisine_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_as_cuisine', to='meal.mealcategoryoption'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_as_meal_type', to='meal.mealcategoryoption'),
        ),
        migrations.AddField(
            model_name='meal',
            name='time_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_as_time', to='meal.mealcategoryoption'),
        ),
        migrations.CreateModel(
            name='MealTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='meal.meal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='meal.mealtag')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meals', through='meal.MealTagAssignment', to='meal.mealtag'),
        ),
        migrations.AddConstraint(
            model_name='mealcategoryoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_user'), models.F('axis'), name='meal_mealcategory_owner_axis_name_lower_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mealtag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_user'), name='meal_mealtag_owner_name_lower_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='mealtagassignment',
            unique_together={('meal', 'tag')},
        ),
    ]
