# Generated by Django migration — seed default category options per user.

from django.conf import settings
from django.db import migrations


def seed_options(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    MealCategoryOption = apps.get_model("meal", "MealCategoryOption")

    meal_types = [
        "Breakfast",
        "Lunch",
        "Dinner",
        "Snack",
        "Entree",
        "Side",
        "Dessert",
        "Soup",
    ]
    cuisines = [
        "Mexican",
        "Thai",
        "French",
        "Italian",
        "American",
        "Chinese",
        "Japanese",
        "Indian",
        "Mediterranean",
    ]
    times = ["Quick", "Average", "Elaborate"]

    for user in User.objects.iterator():
        for name in meal_types:
            MealCategoryOption.objects.get_or_create(
                owner_user_id=user.pk,
                axis="meal_type",
                name=name,
            )
        for name in cuisines:
            MealCategoryOption.objects.get_or_create(
                owner_user_id=user.pk,
                axis="cuisine",
                name=name,
            )
        for name in times:
            MealCategoryOption.objects.get_or_create(
                owner_user_id=user.pk,
                axis="time",
                name=name,
            )


def unseed_options(apps, schema_editor):
    MealCategoryOption = apps.get_model("meal", "MealCategoryOption")
    MealCategoryOption.objects.filter(
        axis="meal_type",
        name__in=[
            "Breakfast",
            "Lunch",
            "Dinner",
            "Snack",
            "Entree",
            "Side",
            "Dessert",
            "Soup",
        ],
    ).delete()
    MealCategoryOption.objects.filter(
        axis="cuisine",
        name__in=[
            "Mexican",
            "Thai",
            "French",
            "Italian",
            "American",
            "Chinese",
            "Japanese",
            "Indian",
            "Mediterranean",
        ],
    ).delete()
    MealCategoryOption.objects.filter(axis="time", name__in=["Quick", "Average", "Elaborate"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0008_meal_tags_categories_publish"),
    ]

    operations = [
        migrations.RunPython(seed_options, unseed_options),
    ]
