# Generated by Django 6.0.3 on 2026-04-11 21:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_seed_meal_category_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylistitem',
            name='contributions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients_vocab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grocery_list_items', to='meal.ingredient'),
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_lines', to='meal.ingredient'),
        ),
        migrations.CreateModel(
            name='SavedGroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_grocery_lists', to=settings.AUTH_USER_MODEL)),
                ('source_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_grocery_snapshots', to='meal.mealplaninstance')),
            ],
            options={
                'ordering': ['-saved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserIngredientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('simple_have', models.BooleanField(blank=True, help_text='When set, use quick have/don’t-have instead of quantity.', null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='meal.ingredient')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredient_inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner_user'), name='meal_ingredient_vocab_owner_name_lower_uniq'),
        ),
        migrations.AddConstraint(
            model_name='useringredientinventory',
            constraint=models.UniqueConstraint(fields=('owner_user', 'ingredient'), name='meal_useringredientinventory_owner_ingredient_uniq'),
        ),
    ]
