# Generated by Django 6.0.3 on 2026-04-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_grocerylist_hide_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='hide_checked',
            field=models.BooleanField(default=False, help_text='UI: hide strikethrough items in the grocery list view.'),
        ),
    ]
